#import "@preview/cades:0.3.1": qr-code
// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "a4",
  flipped: false,
  margin: (top:5mm, bottom:5mm, left:6mm, right:6mm),
)
#set text(size: 8pt, lang: "vi")

// Corner markers
#place(top+left,   dx:-1mm, dy:-1mm, square(size:10pt, fill:black))
#place(top+right,  dx:1mm,  dy:-1mm, square(size:10pt, fill:black))
#place(bottom+left,  dx:-1mm, dy:1mm, square(size:10pt, fill:black))
#place(bottom+right, dx:1mm,  dy:1mm, square(size:10pt, fill:black))

// ── HEADER ──────────────────────────────────────────────────
#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, [
  #grid(columns:(86pt, 54pt, 1fr, 30pt), gutter:0pt, stroke: (x,y) => if x > 0 and x < 3 { (left: 0.5pt) } else { none },
    grid.cell([
      #pad(x: 2pt, y: 4pt)[
        #align(center)[#text(7pt, weight:"bold")[SỐ BÁO DANH]]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*6, row-gutter:2pt, align:center, ..range(6).map(_=>[#rect(width:10pt,height:10pt,stroke:.6pt)]))]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*6, row-gutter:3pt, align:center, ..range(10).map(r => range(6).map(_=>[#circle(radius:4pt,stroke:.4pt)[]])).flatten())]
      ]
    ]),
    grid.cell([
      #pad(x: 2pt, y: 4pt)[
        #align(center)[#text(7pt, weight:"bold")[MÃ ĐỀ THI]]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*3, row-gutter:2pt, align:center, ..range(3).map(_=>[#rect(width:10pt,height:10pt,stroke:.6pt)]))]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*3, row-gutter:3pt, align:center, ..range(10).map(r => range(3).map(_=>[#circle(radius:4pt,stroke:.4pt)[]])).flatten())]
      ]
    ]),
    grid.cell([
      #pad(x:6pt, y: 4pt)[
        #text(9pt, weight:"bold", fill:rgb("#c0392b"))[PHIẾU TRẢ LỜI TRẮC NGHIỆM]
        #v(2pt)
        #text(7pt)[SANG MATH OMR]\
        #text(7pt)[Họ và tên: \....................................................................] \
        #text(7pt)[Lớp: ........................ Môn: ........................ Điểm: ..............]
      ]
    ]),
    grid.cell([
      #pad(x: 4pt, y: 16pt)[
        #align(center)[
          #qr-code("OMR: SANG MATH|Mã đề", width: 24pt)
        ]
      ]
    ])
  )
])


#v(4pt)
#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, [
  #rect(fill:luma(240), width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN II – ĐÚNG / SAI (12 câu, 4 ý a/b/c/d)]]])
  #grid(columns: (1fr,) * 4, stroke: (x,y) => if x > 0 { (left: 0.3pt) } else { none },
    [#pad(x: 4pt, y: 6pt)[#align(center)[#text(7pt, weight:"bold")[Câu 1]]
#v(4pt)
#align(center)[#grid(columns: (12pt, 16pt, 16pt), row-gutter: 6pt, align: horizon,
  [], [#align(center)[#text(6pt)[Đ]]], [#align(center)[#text(6pt)[S]]],
  [#align(right)[#text(6pt)[a)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[b)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[c)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[d)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#text(7pt, weight:"bold")[Câu 2]]
#v(4pt)
#align(center)[#grid(columns: (12pt, 16pt, 16pt), row-gutter: 6pt, align: horizon,
  [], [#align(center)[#text(6pt)[Đ]]], [#align(center)[#text(6pt)[S]]],
  [#align(right)[#text(6pt)[a)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[b)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[c)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[d)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#text(7pt, weight:"bold")[Câu 3]]
#v(4pt)
#align(center)[#grid(columns: (12pt, 16pt, 16pt), row-gutter: 6pt, align: horizon,
  [], [#align(center)[#text(6pt)[Đ]]], [#align(center)[#text(6pt)[S]]],
  [#align(right)[#text(6pt)[a)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[b)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[c)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[d)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#text(7pt, weight:"bold")[Câu 4]]
#v(4pt)
#align(center)[#grid(columns: (12pt, 16pt, 16pt), row-gutter: 6pt, align: horizon,
  [], [#align(center)[#text(6pt)[Đ]]], [#align(center)[#text(6pt)[S]]],
  [#align(right)[#text(6pt)[a)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[b)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[c)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[d)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]]
  )
])



// ── TỰ LUẬN VIẾT TAY ────────────────────────────────────────
#v(4pt)
#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, fill:luma(252), [
  #rect(fill:luma(238), width:100%, height:16pt, [#align(center+horizon)[#text(8pt, fill:gray)[✍ PHẦN TỰ LUẬN – Viết bên dưới]]])
  #v(4pt)
  #set par(leading: 14pt)
  #for _ in range(8) [
    #line(length:100%, stroke:(thickness:.3pt, dash:"dashed", paint:luma(200))) \\
  ]
  #v(4pt)
])
