// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "a5",
  flipped: true,
  fill: white,
  margin: (top: 5mm, bottom: 5mm, left: 6mm, right: 6mm),
)
#set text(size: 8pt, font: "Times New Roman")

#let marker = box(fill: black, width: 12pt, height: 12pt)
#let tracking-marker = box(fill: black, width: 10pt, height: 10pt)

#let bubble(label) = {
  align(center + horizon)[
    #circle(
      radius: 4.5pt,
      stroke: 0.5pt + rgb("#333333"),
      fill: white,
      align(center + horizon)[#text(size: 6.5pt, weight: "regular", fill: rgb("#888888"))[#label]],
    )
  ]
}
#let empty-box = box(stroke: 0.8pt + black, width: if true { 10pt } else { 11pt }, height: if true { 10pt } else { 11pt })
#let qb = box(width: 1.8pt, height: 1.8pt, fill: black)
#let qw = box(width: 1.8pt, height: 1.8pt, fill: white)

#place(top + left, dx: -2mm, dy: -2mm, marker)
#place(top + right, dx: 2mm, dy: -2mm, marker)
#place(bottom + left, dx: -2mm, dy: 2mm, marker)
#place(bottom + right, dx: 2mm, dy: 2mm, marker)
#align(top + center)[
  #scale(x: if true { 88% } else { 95% }, y: if true { 88% } else { 95% }, origin: top)[
    #block(width: 100%, height: 0pt)[
      #place(left, dx: if true { 35mm } else { 43mm }, dy: 15mm)[
        #grid(columns: 21, column-gutter: 0pt, row-gutter: 0pt,
  qb, qb, qb, qb, qb, qb, qb, qw, qw, qb, qw, qb, qb, qw, qb, qb, qb, qb, qb, qb, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qb, qw, qw, qb, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qb, qw, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qw, qw, qw, qb, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qw, qb, qb, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qb, qw, qb, qw, qb, qb, qb, qb, qb, qb, qb,
  qw, qw, qw, qw, qw, qw, qw, qw, qb, qb, qb, qb, qb, qw, qw, qw, qw, qw, qw, qw, qw,
  qb, qb, qw, qb, qw, qw, qb, qb, qw, qb, qb, qw, qw, qw, qb, qb, qb, qw, qb, qb, qw,
  qb, qw, qw, qb, qb, qb, qw, qb, qb, qb, qw, qw, qw, qw, qw, qb, qb, qb, qw, qw, qb,
  qw, qb, qb, qb, qb, qb, qb, qw, qb, qb, qw, qw, qb, qw, qw, qb, qw, qb, qw, qw, qb,
  qb, qb, qw, qb, qw, qw, qw, qb, qw, qw, qb, qb, qw, qw, qb, qb, qb, qw, qw, qb, qb,
  qb, qb, qw, qw, qw, qw, qb, qb, qw, qb, qw, qw, qb, qw, qw, qb, qw, qw, qw, qb, qb,
  qw, qw, qw, qw, qw, qw, qw, qw, qb, qb, qb, qb, qw, qw, qw, qb, qw, qw, qb, qw, qb,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qb, qw, qw, qw, qb, qw, qb, qb, qw, qb, qb, qw,
  qb, qw, qw, qw, qw, qw, qb, qw, qw, qb, qb, qb, qb, qw, qw, qw, qw, qb, qw, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qb, qb, qw, qb, qw, qb, qb, qb, qw, qb, qw,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qw, qw, qw, qw, qw, qw, qb, qb, qw, qw, qb, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qb, qw, qw, qw, qb, qw, qw, qw, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qw, qb, qb, qw, qb, qb, qb, qw, qw, qw,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qw, qw, qb, qw, qb, qw, qb, qw, qw, qb, qw
)
      ]
    ]
    

// ── HEADER ──────────────────────────────────────────────────
#let sbd-box = block(
  inset: (left: if true { 6pt } else { 4pt }, right: if true { 3pt } else { 2pt }, top: if true { 1pt } else { 2pt }, bottom: if true { 1pt } else { 2pt }),
  [
    #place(top + left, dx: -2pt, dy: -2pt)[#tracking-marker]
        #align(center)[#text(weight: "bold", size: 8pt)[SỐ BÁO DANH]]
    #v(if true { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 6, gutter: if true { 1.2pt } else { 1.5pt },
      ..range(6).map(i => align(center, empty-box))
    )
    #v(if true { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 6, row-gutter: if true { 0.8pt } else { 1.5pt }, column-gutter: 1.5pt,
      ..range(10).map(r => range(6).map(c => bubble(str(r)))).flatten()
    )
  ],
)

#let made-box = block(
  inset: (left: if true { 3pt } else { 2pt }, right: if true { 3pt } else { 2pt }, top: if true { 1pt } else { 2pt }, bottom: if true { 1pt } else { 2pt }),
  [
    #place(top + left, dx: -2pt, dy: -2pt)[#tracking-marker]
        #align(right)[#text(weight: "bold", size: 8pt)[MÃ ĐỀ THI]]
    #v(if true { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 4,
      gutter: if true { 1.2pt } else { 1.5pt },
      align(center, empty-box), align(center, empty-box), align(center, empty-box), align(center, empty-box),
    )
    #v(if true { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 4, row-gutter: if true { 0.8pt } else { 1.5pt }, column-gutter: 1.5pt,
      ..range(10).map(r => range(4).map(c => bubble(str(r)))).flatten()
    )
  ],
)

#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #grid(columns:(82pt, 60pt, 1fr, 28pt), gutter:0pt, stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), sbd-box),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), made-box),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), [
      #pad(x:4pt)[
        #text(10pt, weight:"bold", fill:rgb("#c0392b"))[PHIẾU TRẢ LỜI TRẮC NGHIỆM]
        #v(2pt)
        #text(7pt)[SANG MATH OMR]
        #v(4pt)
        #text(7pt)[Họ và tên: .....................................................]
        #v(4pt)
        #text(7pt)[Lớp: ............ Môn: ............... Điểm: ...............]
      ]
    ]),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), [
      #align(center+horizon)[
        #rect(width:24pt, height:24pt, stroke:.5pt)[
          #align(center+horizon)[#text(6pt, fill:gray)[QR]]
        ]
      ]
    ]),
  )
])



#v(4pt)
#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN II – ĐÚNG / SAI (20 câu, mỗi câu 4 ý a/b/c/d)]]])
  #scale(x: 88%, y: 88%, origin: top)[
  #block(
    inset: (top: 3pt, bottom: 3pt, left: 8pt, right: 8pt),
    grid(
      columns: (1fr,) * 5,
      row-gutter: 1pt,
      column-gutter: 5pt,
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 1]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 2]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 3]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 4]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 5]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 6]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 7]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 8]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 9]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 10]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 11]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 12]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 13]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 14]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 15]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 16]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 17]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 18]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 19]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 1pt,
        column-gutter: 2pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 1pt,
            box(fill: black, width: 7pt, height: 7pt),
            text(size: 7pt, weight: "bold")[Câu 20]
          )
        ],
        none, text(size: 7pt, weight: "bold")[Đ], text(size: 7pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      )
    )
  )
  ]
])


// ── TỰ LUẬN VIẾT TAY ────────────────────────────────────────


  ]
]
