// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "a5",
  flipped: true,
  fill: white,
  margin: (top: 5mm, bottom: 5mm, left: 6mm, right: 6mm),
)
#set text(size: 8pt, font: "Times New Roman")

#let marker = box(fill: black, width: 12pt, height: 12pt)
#let tracking-marker = box(fill: black, width: 10pt, height: 10pt)

#let bubble(label) = {
  align(center + horizon)[
    #circle(
      radius: 4.5pt,
      stroke: 0.5pt + rgb("#333333"),
      fill: white,
      align(center + horizon)[#text(size: 6.5pt, weight: "regular", fill: rgb("#888888"))[#label]]
    )
  ]
}
#let empty-box = box(stroke: 0.8pt + black, width: if true { 10pt } else { 11pt }, height: if true { 10pt } else { 11pt })
#let qb = box(width: 1.8pt, height: 1.8pt, fill: black)
#let qw = box(width: 1.8pt, height: 1.8pt, fill: white)

#place(top + left, dx: -2mm, dy: -2mm, marker)
#place(top + right, dx: 2mm, dy: -2mm, marker)
#place(bottom + left, dx: -2mm, dy: 2mm, marker)
#place(bottom + right, dx: 2mm, dy: 2mm, marker)
#align(top + center)[
  #scale(x: if true { 88% } else { 95% }, y: if true { 88% } else { 95% }, origin: top)[
    #block(width: 100%, height: 0pt)[
      #place(left, dx: if true { 35mm } else { 43mm }, dy: 15mm)[
        #grid(columns: 21, column-gutter: 0pt, row-gutter: 0pt,
  qb, qb, qb, qb, qb, qb, qb, qw, qw, qb, qw, qb, qb, qw, qb, qb, qb, qb, qb, qb, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qb, qw, qw, qb, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw, qb, qw, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qb, qw, qb, qw, qb, qb, qb, qb, qb, qb, qb,
  qw, qw, qw, qw, qw, qw, qw, qw, qb, qw, qw, qb, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qb, qb, qb, qb, qb, qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qb, qb, qb, qw,
  qb, qw, qb, qw, qw, qb, qw, qb, qw, qb, qb, qb, qb, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw, qw, qw, qw, qb, qb, qw, qb, qw,
  qb, qb, qb, qw, qw, qw, qb, qw, qw, qb, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qb,
  qw, qw, qw, qw, qw, qw, qw, qw, qb, qb, qw, qw, qw, qw, qb, qw, qw, qb, qb, qw, qw,
  qb, qb, qb, qb, qb, qb, qb, qw, qw, qw, qw, qb, qb, qb, qb, qb, qw, qb, qb, qb, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qb, qw, qw, qb, qw, qw, qb, qb, qb, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qb, qb, qw, qb, qw, qw, qw, qw, qw, qw, qw,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qb, qb, qw, qb, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qb, qw, qb, qw, qb, qb, qw, qw, qw,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qb, qw, qb, qw, qw, qb, qb, qw, qb, qb,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qw, qw, qb, qw, qw, qb, qw,
        )
      ]
    ]

// ── HEADER ──────────────────────────────────────────────────
#grid(
  columns: (1fr, auto, 1fr),
  align: center + horizon,
  none,
  align(center)[
    #text(size: 14pt, weight: "bold", fill: rgb("#d32f2f"))[PHIẾU TRẢ LỜI TRẮC NGHIỆM]
  ],
  none
)
#v(4pt)

// Thêm block bao quanh thông tin học sinh
#block(
  width: 100%,
  stroke: (paint: rgb("#666666"), thickness: 0.5pt, dash: "dashed"),
  radius: 4pt,
  inset: 5pt,
  clip: true,
  [
    #grid(
      columns: (6fr, 4fr, 4fr),
      column-gutter: 10pt,
      align: left + horizon,
      [
        #text(size: 9pt, weight: "bold")[Họ và tên học sinh: ] ..............................................................
        #v(4pt)
        #text(size: 9pt, weight: "bold")[Lớp: ] ....................................................................................
      ],
      [
        #align(center)[#text(size: 9pt, weight: "bold")[Số Báo Danh]]
        #v(2pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt, 12pt, 12pt),
          align: center,
          tracking-marker, empty-box, empty-box, empty-box, empty-box, empty-box,
        )
        #v(1pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt, 12pt, 12pt),
          rows: (11pt,) * 10,
          align: center + horizon,
          ..range(0, 10).map(r => (
            [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble("0"), bubble("0"), bubble("0"), bubble("0"), bubble("0")
          )).flatten(),
        )
      ],
      [
        #align(center)[#text(size: 9pt, weight: "bold")[Mã đề thi]]
        #v(2pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt),
          align: center,
          tracking-marker, empty-box, empty-box, empty-box,
        )
        #v(1pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt),
          rows: (11pt,) * 10,
          align: center + horizon,
          ..range(0, 10).map(r => (
            [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble("0"), bubble("0"), bubble("0")
          )).flatten(),
        )
      ]
    )
  ]
)
// ── PHẦN ĐÚNG/SAI ──────────────────────────────────────────
#v(if true { -2pt } else { 4pt })
#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN II – ĐÚNG / SAI (20 câu, mỗi câu 4 ý a/b/c/d)]]])
  #block(
    inset: (top: 8pt, bottom: 8pt, left: 10pt, right: 10pt),
    grid(
      columns: (1fr,) * 5,
      row-gutter: 4pt,
      column-gutter: 8pt,
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 1]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 5]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 9]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 13]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 17]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 2]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 6]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 10]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 14]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 18]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 3]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 7]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 11]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 15]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 19]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 4]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 8]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 12]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 16]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu 20]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),
    )
  )
])
// ── PHẦN TỰ LUẬN NGẮN ──────────────────────────────────────
#v(if true { -2pt } else { 4pt })
#scale(x: 75%, y: 75%, origin: top + left)[
#block(width:133.33333333333334%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN III – TỰ LUẬN NGẮN (Câu 1-10)]]])
  #block(
    inset: (left: 10pt, right: 10pt, top: if true { 3pt } else { 0pt }, bottom: if true { 5pt } else { 6pt }),
    grid(
      columns: (1fr,) * 5,
      row-gutter: 4pt,
      block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 1*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 3*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 5*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 7*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 9*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 2*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 4*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 6*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 8*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),       block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 10*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ),     )
  )
])
]
// ── TỰ LUẬN VIẾT TAY ────────────────────────────────────────


  ]
]
