#import "@preview/cades:0.3.1": qr-code
// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "a4",
  flipped: false,
  margin: (top:5mm, bottom:5mm, left:6mm, right:6mm),
)
#set text(size: 8pt, lang: "vi")

// Corner markers
#place(top+left,   dx:-1mm, dy:-1mm, square(size:10pt, fill:black))
#place(top+right,  dx:1mm,  dy:-1mm, square(size:10pt, fill:black))
#place(bottom+left,  dx:-1mm, dy:1mm, square(size:10pt, fill:black))
#place(bottom+right, dx:1mm,  dy:1mm, square(size:10pt, fill:black))

// ── HEADER ──────────────────────────────────────────────────
#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, [
  #grid(columns:(86pt, 54pt, 1fr, 30pt), gutter:0pt, stroke: (x,y) => if x > 0 and x < 3 { (left: 0.5pt) } else { none },
    grid.cell([
      #pad(x: 2pt, y: 4pt)[
        #align(center)[#text(7pt, weight:"bold")[SỐ BÁO DANH]]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*6, row-gutter:2pt, align:center, ..range(6).map(_=>[#rect(width:10pt,height:10pt,stroke:.6pt)]))]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*6, row-gutter:3pt, align:center, ..range(10).map(r => range(6).map(_=>[#circle(radius:4pt,stroke:.4pt)[]])).flatten())]
      ]
    ]),
    grid.cell([
      #pad(x: 2pt, y: 4pt)[
        #align(center)[#text(7pt, weight:"bold")[MÃ ĐỀ THI]]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*3, row-gutter:2pt, align:center, ..range(3).map(_=>[#rect(width:10pt,height:10pt,stroke:.6pt)]))]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*3, row-gutter:3pt, align:center, ..range(10).map(r => range(3).map(_=>[#circle(radius:4pt,stroke:.4pt)[]])).flatten())]
      ]
    ]),
    grid.cell([
      #pad(x:6pt, y: 4pt)[
        #text(9pt, weight:"bold", fill:rgb("#c0392b"))[PHIẾU TRẢ LỜI TRẮC NGHIỆM]
        #v(2pt)
        #text(7pt)[SANG MATH OMR]\
        #text(7pt)[Họ và tên: \....................................................................] \
        #text(7pt)[Lớp: ........................ Môn: ........................ Điểm: ..............]
      ]
    ]),
    grid.cell([
      #pad(x: 4pt, y: 16pt)[
        #align(center)[
          #qr-code("OMR: SANG MATH|Mã đề", width: 24pt)
        ]
      ]
    ])
  )
])

#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, [
  #rect(fill:luma(240), width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN I – TRẮC NGHIỆM (12 câu, chọn 1 đáp án)]]])
  #grid(columns: (1fr,) * 2, stroke: (x,y) => if x > 0 { (left: 0.3pt) } else { none },
    [#pad(x: 4pt, y: 6pt)[#align(center)[#grid(columns: (18pt, 14pt, 14pt, 14pt, 14pt), row-gutter: 4pt, align: horizon,
  [], [#align(center)[#text(6pt)[A]]], [#align(center)[#text(6pt)[B]]], [#align(center)[#text(6pt)[C]]], [#align(center)[#text(6pt)[D]]],
  [#align(right)[#text(7pt)[1.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[2.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[3.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[4.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[5.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[6.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#grid(columns: (18pt, 14pt, 14pt, 14pt, 14pt), row-gutter: 4pt, align: horizon,
  [], [#align(center)[#text(6pt)[A]]], [#align(center)[#text(6pt)[B]]], [#align(center)[#text(6pt)[C]]], [#align(center)[#text(6pt)[D]]],
  [#align(right)[#text(7pt)[7.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[8.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[9.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[10.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[11.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[12.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]]
  )
])

#v(4pt)
#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, [
  #rect(fill:luma(240), width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN II – ĐÚNG / SAI (4 câu, 4 ý a/b/c/d)]]])
  #grid(columns: (1fr,) * 4, stroke: (x,y) => if x > 0 { (left: 0.3pt) } else { none },
    [#pad(x: 4pt, y: 6pt)[#align(center)[#text(7pt, weight:"bold")[Câu 1]]
#v(4pt)
#align(center)[#grid(columns: (12pt, 16pt, 16pt), row-gutter: 6pt, align: horizon,
  [], [#align(center)[#text(6pt)[Đ]]], [#align(center)[#text(6pt)[S]]],
  [#align(right)[#text(6pt)[a)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[b)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[c)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[d)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#text(7pt, weight:"bold")[Câu 2]]
#v(4pt)
#align(center)[#grid(columns: (12pt, 16pt, 16pt), row-gutter: 6pt, align: horizon,
  [], [#align(center)[#text(6pt)[Đ]]], [#align(center)[#text(6pt)[S]]],
  [#align(right)[#text(6pt)[a)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[b)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[c)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[d)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#text(7pt, weight:"bold")[Câu 3]]
#v(4pt)
#align(center)[#grid(columns: (12pt, 16pt, 16pt), row-gutter: 6pt, align: horizon,
  [], [#align(center)[#text(6pt)[Đ]]], [#align(center)[#text(6pt)[S]]],
  [#align(right)[#text(6pt)[a)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[b)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[c)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[d)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#text(7pt, weight:"bold")[Câu 4]]
#v(4pt)
#align(center)[#grid(columns: (12pt, 16pt, 16pt), row-gutter: 6pt, align: horizon,
  [], [#align(center)[#text(6pt)[Đ]]], [#align(center)[#text(6pt)[S]]],
  [#align(right)[#text(6pt)[a)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[b)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[c)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(6pt)[d)]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]]
  )
])

  #v(4pt)
  #block(width:100%, stroke:0.8pt, radius:4pt, clip:true, [
    #rect(fill:luma(240), width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN III – TỰ LUẬN NGẮN (Câu 1–6)]]])
    #grid(columns: (1fr,) * 6, stroke: (x,y) => if x > 0 { (left: 0.3pt) } else { none },
      [#pad(x: 2pt, y: 4pt)[#align(center)[#text(7pt,weight:"bold")[Câu 1]]
#v(2pt)
#align(center)[#box(fill:black,width:8pt,height:8pt) #h(2pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[]]
#v(4pt)
#align(center)[#grid(columns: (10pt, 13pt, 13pt, 13pt, 13pt), row-gutter: 4pt, align: horizon,
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[-]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[,]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[0]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[1]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[2]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[3]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[4]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[5]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[6]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[7]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[8]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[9]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
)]]],
      [#pad(x: 2pt, y: 4pt)[#align(center)[#text(7pt,weight:"bold")[Câu 2]]
#v(2pt)
#align(center)[#box(fill:black,width:8pt,height:8pt) #h(2pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[]]
#v(4pt)
#align(center)[#grid(columns: (10pt, 13pt, 13pt, 13pt, 13pt), row-gutter: 4pt, align: horizon,
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[-]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[,]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[0]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[1]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[2]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[3]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[4]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[5]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[6]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[7]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[8]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[9]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
)]]],
      [#pad(x: 2pt, y: 4pt)[#align(center)[#text(7pt,weight:"bold")[Câu 3]]
#v(2pt)
#align(center)[#box(fill:black,width:8pt,height:8pt) #h(2pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[]]
#v(4pt)
#align(center)[#grid(columns: (10pt, 13pt, 13pt, 13pt, 13pt), row-gutter: 4pt, align: horizon,
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[-]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[,]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[0]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[1]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[2]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[3]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[4]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[5]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[6]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[7]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[8]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[9]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
)]]],
      [#pad(x: 2pt, y: 4pt)[#align(center)[#text(7pt,weight:"bold")[Câu 4]]
#v(2pt)
#align(center)[#box(fill:black,width:8pt,height:8pt) #h(2pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[]]
#v(4pt)
#align(center)[#grid(columns: (10pt, 13pt, 13pt, 13pt, 13pt), row-gutter: 4pt, align: horizon,
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[-]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[,]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[0]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[1]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[2]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[3]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[4]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[5]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[6]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[7]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[8]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[9]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
)]]],
      [#pad(x: 2pt, y: 4pt)[#align(center)[#text(7pt,weight:"bold")[Câu 5]]
#v(2pt)
#align(center)[#box(fill:black,width:8pt,height:8pt) #h(2pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[]]
#v(4pt)
#align(center)[#grid(columns: (10pt, 13pt, 13pt, 13pt, 13pt), row-gutter: 4pt, align: horizon,
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[-]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[,]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[0]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[1]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[2]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[3]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[4]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[5]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[6]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[7]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[8]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[9]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
)]]],
      [#pad(x: 2pt, y: 4pt)[#align(center)[#text(7pt,weight:"bold")[Câu 6]]
#v(2pt)
#align(center)[#box(fill:black,width:8pt,height:8pt) #h(2pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[] #h(1pt) #box(width:9pt,height:9pt,stroke:.5pt)[]]
#v(4pt)
#align(center)[#grid(columns: (10pt, 13pt, 13pt, 13pt, 13pt), row-gutter: 4pt, align: horizon,
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[-]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[,]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[0]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[1]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[2]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[3]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[4]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[5]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[6]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[7]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[8]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
  [#align(right)[#text(5.5pt, fill: rgb("#444"))[9]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:4pt,stroke:.4pt)[]]],
)]]]
    )
  ])


// ── TỰ LUẬN VIẾT TAY ────────────────────────────────────────
#v(4pt)
#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, fill:luma(252), [
  #rect(fill:luma(238), width:100%, height:16pt, [#align(center+horizon)[#text(8pt, fill:gray)[✍ PHẦN TỰ LUẬN – Viết bên dưới]]])
  #v(4pt)
  #set par(leading: 14pt)
  #for _ in range(8) [
    #line(length:100%, stroke:(thickness:.3pt, dash:"dashed", paint:luma(200))) \\
  ]
  #v(4pt)
])
