// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "a5",
  flipped: true,
  fill: white,
  margin: (top: 5mm, bottom: 5mm, left: 6mm, right: 6mm),
)
#set text(size: 8pt, font: "Times New Roman")

#let marker = box(fill: black, width: 12pt, height: 12pt)
#let tracking-marker = box(fill: black, width: 10pt, height: 10pt)

#let bubble(label) = {
  align(center + horizon)[
    #circle(
      radius: 4.5pt,
      stroke: 0.5pt + rgb("#333333"),
      fill: white,
      align(center + horizon)[#text(size: 6.5pt, weight: "regular", fill: rgb("#888888"))[#label]],
    )
  ]
}
#let empty-box = box(stroke: 0.8pt + black, width: if true { 10pt } else { 11pt }, height: if true { 10pt } else { 11pt })
#let qb = box(width: 1.8pt, height: 1.8pt, fill: black)
#let qw = box(width: 1.8pt, height: 1.8pt, fill: white)

#place(top + left, dx: -2mm, dy: -2mm, marker)
#place(top + right, dx: 2mm, dy: -2mm, marker)
#place(bottom + left, dx: -2mm, dy: 2mm, marker)
#place(bottom + right, dx: 2mm, dy: 2mm, marker)
#align(top + center)[
  #scale(x: if true { 88% } else { 95% }, y: if true { 88% } else { 95% }, origin: top)[
    #block(width: 100%, height: 0pt)[
      #place(left, dx: if true { 35mm } else { 43mm }, dy: 15mm)[
        #grid(columns: 21, column-gutter: 0pt, row-gutter: 0pt,
  qb, qb, qb, qb, qb, qb, qb, qw, qw, qb, qb, qb, qb, qw, qb, qb, qb, qb, qb, qb, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qw, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qb, qb, qb, qw, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qw, qw, qb, qw, qb, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qb, qw, qb, qw, qb, qb, qb, qb, qb, qb, qb,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qb, qb, qb, qb, qw, qw, qw, qw, qw, qw, qw, qw,
  qb, qb, qw, qw, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qw, qb, qb, qw, qw, qw,
  qw, qw, qb, qw, qw, qb, qw, qb, qw, qb, qb, qw, qb, qb, qw, qw, qw, qb, qw, qw, qw,
  qw, qb, qw, qb, qb, qw, qb, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qw, qb, qb, qw,
  qw, qb, qw, qw, qw, qb, qw, qb, qw, qb, qb, qw, qw, qb, qw, qb, qw, qb, qb, qw, qw,
  qw, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw, qw, qw, qb, qw, qw, qw, qb, qw, qw, qb,
  qw, qw, qw, qw, qw, qw, qw, qw, qb, qb, qb, qw, qb, qb, qw, qw, qb, qb, qw, qb, qb,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qw, qw, qb, qb, qb, qb, qw, qw, qw, qb, qw,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qb, qw, qb, qb, qw, qb, qw, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qb, qb, qw, qb, qb, qw, qw, qw, qb, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qw, qw, qw, qb, qb, qb, qw, qw, qw,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qb, qw, qb, qb, qb, qw, qb, qb, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qw, qw, qb, qw, qb, qw, qw, qb, qw, qw,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qb, qw, qb, qw, qw, qb, qb, qw, qb, qw, qb, qw
)
      ]
    ]
    

// ── HEADER ──────────────────────────────────────────────────
#let sbd-box = block(
  inset: (left: if true { 6pt } else { 4pt }, right: if true { 3pt } else { 2pt }, top: if true { 1pt } else { 2pt }, bottom: if true { 1pt } else { 2pt }),
  [
    #place(top + left, dx: -2pt, dy: -2pt)[#tracking-marker]
        #align(center)[#text(weight: "bold", size: 8pt)[SỐ BÁO DANH]]
    #v(if true { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 6, gutter: if true { 1.2pt } else { 1.5pt },
      ..range(6).map(i => align(center, empty-box))
    )
    #v(if true { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 6, row-gutter: if true { 0.8pt } else { 1.5pt }, column-gutter: 1.5pt,
      ..range(10).map(r => range(6).map(c => bubble(str(r)))).flatten()
    )
  ],
)

#let made-box = block(
  inset: (left: if true { 3pt } else { 2pt }, right: if true { 3pt } else { 2pt }, top: if true { 1pt } else { 2pt }, bottom: if true { 1pt } else { 2pt }),
  [
    #place(top + left, dx: -2pt, dy: -2pt)[#tracking-marker]
        #align(right)[#text(weight: "bold", size: 8pt)[MÃ ĐỀ THI]]
    #v(if true { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 4,
      gutter: if true { 1.2pt } else { 1.5pt },
      align(center, empty-box), align(center, empty-box), align(center, empty-box), align(center, empty-box),
    )
    #v(if true { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 4, row-gutter: if true { 0.8pt } else { 1.5pt }, column-gutter: 1.5pt,
      ..range(10).map(r => range(4).map(c => bubble(str(r)))).flatten()
    )
  ],
)

#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #grid(columns:(82pt, 60pt, 1fr, 28pt), gutter:0pt, stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), sbd-box),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), made-box),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), [
      #pad(x:4pt)[
        #text(10pt, weight:"bold", fill:rgb("#c0392b"))[PHIẾU TRẢ LỜI TRẮC NGHIỆM]
        #v(2pt)
        #text(7pt)[SANG MATH OMR]
        #v(4pt)
        #text(7pt)[Họ và tên: .....................................................]
        #v(4pt)
        #text(7pt)[Lớp: ............ Môn: ............... Điểm: ...............]
      ]
    ]),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), [
      #align(center+horizon)[
        #rect(width:24pt, height:24pt, stroke:.5pt)[
          #align(center+horizon)[#text(6pt, fill:gray)[QR]]
        ]
      ]
    ]),
  )
])



#scale(x: 75%, y: 75%, origin: top + left)[

#v(if true { -2pt } else { 4pt })
#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN III – TỰ LUẬN NGẮN (Câu 1-5)]]])
  #block(
    inset: (left: 10pt, right: 10pt, top: if true { 3pt } else { 0pt }, bottom: if true { 5pt } else { 6pt }),
    grid(
      columns: (1fr,) * 5,
      row-gutter: 4pt,
      block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 1*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 2*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 3*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 4*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 5*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      )
    )
  )
])

#v(if true { -2pt } else { 4pt })
#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN IV – TỰ LUẬN NGẮN (Câu 6-10)]]])
  #block(
    inset: (left: 10pt, right: 10pt, top: if true { 3pt } else { 0pt }, bottom: if true { 5pt } else { 6pt }),
    grid(
      columns: (1fr,) * 5,
      row-gutter: 4pt,
      block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 6*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 7*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 8*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 9*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if true { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu 10*]]
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if true { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if true { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], [], bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      )
    )
  )
])
]

// ── TỰ LUẬN VIẾT TAY ────────────────────────────────────────

#v(4pt)
#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[✍ PHẦN TỰ LUẬN – Viết bên dưới]]])
  #v(4pt)
  #set par(leading: 14pt)
  #for _ in range(4) [
    #line(length:100%, stroke:(thickness:.3pt, dash:"dashed", paint:luma(200)))
    #v(14pt)
  ]
  #v(4pt)
])

  ]
]
