#import "@preview/cades:0.3.1": qr-code
// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "a4",
  flipped: false,
  margin: (top:5mm, bottom:5mm, left:6mm, right:6mm),
)
#set text(size: 8pt, lang: "vi")

// Corner markers
#place(top+left,   dx:-1mm, dy:-1mm, square(size:10pt, fill:black))
#place(top+right,  dx:1mm,  dy:-1mm, square(size:10pt, fill:black))
#place(bottom+left,  dx:-1mm, dy:1mm, square(size:10pt, fill:black))
#place(bottom+right, dx:1mm,  dy:1mm, square(size:10pt, fill:black))

// ── HEADER ──────────────────────────────────────────────────
#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, [
  #grid(columns:(86pt, 54pt, 1fr, 30pt), gutter:0pt, stroke: (x,y) => if x > 0 and x < 3 { (left: 0.5pt) } else { none },
    grid.cell([
      #pad(x: 2pt, y: 4pt)[
        #align(center)[#text(7pt, weight:"bold")[SỐ BÁO DANH]]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*6, row-gutter:2pt, align:center, ..range(6).map(_=>[#rect(width:10pt,height:10pt,stroke:.6pt)]))]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*6, row-gutter:3pt, align:center, ..range(10).map(r => range(6).map(_=>[#circle(radius:4pt,stroke:.4pt)[]])).flatten())]
      ]
    ]),
    grid.cell([
      #pad(x: 2pt, y: 4pt)[
        #align(center)[#text(7pt, weight:"bold")[MÃ ĐỀ THI]]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*3, row-gutter:2pt, align:center, ..range(3).map(_=>[#rect(width:10pt,height:10pt,stroke:.6pt)]))]
        #v(4pt)
        #align(center)[#grid(columns:(1fr,)*3, row-gutter:3pt, align:center, ..range(10).map(r => range(3).map(_=>[#circle(radius:4pt,stroke:.4pt)[]])).flatten())]
      ]
    ]),
    grid.cell([
      #pad(x:6pt, y: 4pt)[
        #text(9pt, weight:"bold", fill:rgb("#c0392b"))[PHIẾU TRẢ LỜI TRẮC NGHIỆM]
        #v(2pt)
        #text(7pt)[SANG MATH OMR]\
        #text(7pt)[Họ và tên: \....................................................................] \
        #text(7pt)[Lớp: ........................ Môn: ........................ Điểm: ..............]
      ]
    ]),
    grid.cell([
      #pad(x: 4pt, y: 16pt)[
        #align(center)[
          #qr-code("OMR: SANG MATH|Mã đề", width: 24pt)
        ]
      ]
    ])
  )
])

#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, [
  #rect(fill:luma(240), width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN I – TRẮC NGHIỆM (60 câu, chọn 1 đáp án)]]])
  #grid(columns: (1fr,) * 4, stroke: (x,y) => if x > 0 { (left: 0.3pt) } else { none },
    [#pad(x: 4pt, y: 6pt)[#align(center)[#grid(columns: (18pt, 14pt, 14pt, 14pt, 14pt), row-gutter: 4pt, align: horizon,
  [], [#align(center)[#text(6pt)[A]]], [#align(center)[#text(6pt)[B]]], [#align(center)[#text(6pt)[C]]], [#align(center)[#text(6pt)[D]]],
  [#align(right)[#text(7pt)[1.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[2.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[3.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[4.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[5.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[6.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[7.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[8.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[9.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[10.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[11.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[12.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[13.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[14.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[15.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#grid(columns: (18pt, 14pt, 14pt, 14pt, 14pt), row-gutter: 4pt, align: horizon,
  [], [#align(center)[#text(6pt)[A]]], [#align(center)[#text(6pt)[B]]], [#align(center)[#text(6pt)[C]]], [#align(center)[#text(6pt)[D]]],
  [#align(right)[#text(7pt)[16.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[17.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[18.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[19.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[20.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[21.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[22.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[23.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[24.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[25.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[26.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[27.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[28.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[29.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[30.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#grid(columns: (18pt, 14pt, 14pt, 14pt, 14pt), row-gutter: 4pt, align: horizon,
  [], [#align(center)[#text(6pt)[A]]], [#align(center)[#text(6pt)[B]]], [#align(center)[#text(6pt)[C]]], [#align(center)[#text(6pt)[D]]],
  [#align(right)[#text(7pt)[31.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[32.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[33.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[34.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[35.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[36.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[37.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[38.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[39.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[40.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[41.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[42.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[43.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[44.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[45.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]],
    [#pad(x: 4pt, y: 6pt)[#align(center)[#grid(columns: (18pt, 14pt, 14pt, 14pt, 14pt), row-gutter: 4pt, align: horizon,
  [], [#align(center)[#text(6pt)[A]]], [#align(center)[#text(6pt)[B]]], [#align(center)[#text(6pt)[C]]], [#align(center)[#text(6pt)[D]]],
  [#align(right)[#text(7pt)[46.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[47.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[48.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[49.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[50.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[51.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[52.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[53.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[54.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[55.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[56.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[57.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[58.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[59.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
  [#align(right)[#text(7pt)[60.]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]], [#align(center)[#circle(radius:5pt,stroke:.4pt)[]]],
)]]]
  )
])




// ── TỰ LUẬN VIẾT TAY ────────────────────────────────────────
#v(4pt)
#block(width:100%, stroke:0.8pt, radius:4pt, clip:true, fill:luma(252), [
  #rect(fill:luma(238), width:100%, height:16pt, [#align(center+horizon)[#text(8pt, fill:gray)[✍ PHẦN TỰ LUẬN – Viết bên dưới]]])
  #v(4pt)
  #set par(leading: 14pt)
  #for _ in range(8) [
    #line(length:100%, stroke:(thickness:.3pt, dash:"dashed", paint:luma(200))) \\
  ]
  #v(4pt)
])
