// main.typ — Chỉ include đề, mọi cấu hình trong file đề
// #include "exams/de-01.typ"
// #include "exams/1-dem.typ"
// #include "exams/CD-MatCau.typ"
// #include "exams/CD-Parabol.typ"
// #include "exams/Đánh-Trận-Có Vận Tốc.typ"
// #include "exams/Da-Giac-Deu.typ"
// #include "exams/Cầu Bị Gió Thổi.typ"
// #include "exams/Xác-Suât-Đối Kháng.typ"
// #include "exams/Sơ-Đồ-Cây-1-3-6.typ"
// #include "exams/CD-Goc-Khoang-Cach.typ"
#include "exams/Tốc Độ Vật Trượt.typ"
#include "exams/Parabol-Oxyz-Có-Vận-Tốc.typ"
// #include "exams/Parabol-Oxyz.typ"
// #include "exams/Dien-Tich-Conic-Ẩn.typ"
// #include "exams/CD-Hai-con-bo.typ"
// #include "exams/CD-tich-Phan-đọc lạ.typ" 
// #include "exams/CD-Đếm Nâng Cao.typ"
// #include "exams/Sơ-Đồ-Cây-2-4-8.typ"

// #include "exams/Di-Chuyển-Qua-Nhiều-Môi-Trường-Có-Vận-Tốc.typ"
// #include "exams/CD-HHKG.typ"
// #include "exams/CD-tich-Phan-đọc lạ.typ" 
// #include "exams/Xác-Suất-Bốc-Bi.typ"
// #include "exams/CHủ Đề Thay Đổi Bảo Hoà.typ"