const fs = require('fs');

const indexHtml = fs.readFileSync('index.html', 'utf8');

const regex = /function genWasmTypst\(\{ mcq, tf, tln, paper, school, subtitle \}\) \{[\s\S]*?return `\/\/ Preview-safe Typst[\s\S]*?\n\}`;/;

const newFn = `function genWasmTypst({ mcq, tf, tln, paper, school, subtitle }) {
    const isA5 = paper === 'a5';
    
    // Typst macros and setup
    const macros = \`// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "\${isA5 ? 'a5' : 'a4'}",
  flipped: \${isA5},
  margin: (top: 5mm, bottom: 5mm, left: 6mm, right: 6mm),
)
#set text(size: 8pt, font: "Times New Roman")

#let marker = box(fill: black, width: 12pt, height: 12pt)
#let tracking-marker = box(fill: black, width: 10pt, height: 10pt)

#let bubble(label) = {
  circle(
    radius: 5pt,
    stroke: 0.5pt + rgb("#333333"),
    fill: white,
    align(center + horizon)[#text(size: 7pt, weight: "bold", fill: rgb("#444444"))[#label]],
  )
}

#let empty-box = box(stroke: 0.8pt + black, width: 11pt, height: 11pt)

#align(center + horizon)[
  #scale(x: 95%, y: 95%, origin: center)[
    #place(top + left, dx: -5mm, dy: -5mm, marker)
    #place(top + right, dx: 5mm, dy: -5mm, marker)
    #place(bottom + left, dx: -5mm, dy: 5mm, marker)
    #place(bottom + right, dx: 5mm, dy: 5mm, marker)
    #v(2pt)
\`;

    const header = \`    #let sbd-box = block(
      inset: (left: 2pt, right: 2pt, top: 2pt, bottom: 2pt),
      [
        #align(center)[#text(weight: "bold", size: 8pt)[SBD]]
        #v(2pt)
        #grid(
          columns: (12pt,) * 6, gutter: 1.5pt,
          ..range(6).map(i => align(center, empty-box))
        )
        #v(2pt)
        #grid(
          columns: (12pt,) * 6, row-gutter: 1.5pt, column-gutter: 1.5pt,
          ..range(10).map(r => range(6).map(c => align(center, bubble(str(r))))).flatten()
        )
      ],
    )
    
    #let made-box = block(
      inset: (left: 2pt, right: 2pt, top: 2pt, bottom: 2pt),
      [
        #align(center)[#text(weight: "bold", size: 8pt)[Mã đề]]
        #v(2pt)
        #grid(
          columns: (12pt,) * 3,
          gutter: 1.5pt,
          align(center, empty-box), align(center, empty-box), align(center, empty-box),
        )
        #v(2pt)
        #grid(
          columns: (12pt,) * 3, row-gutter: 1.5pt, column-gutter: 1.5pt,
          ..range(10).map(r => range(3).map(c => align(center, bubble(str(r))))).flatten()
        )
      ],
    )
\`;

    // MCQ
    const cols = mcq <= 20 ? 2 : mcq <= 40 ? 3 : 4;
    const perCol = mcq > 0 ? Math.ceil(mcq / cols) : 0;
    
    let mcqSection = '';
    if (mcq > 0) {
        let colBlocks = [];
        for (let c=0; c<cols; c++) {
            const start = c * perCol + 1;
            const end = Math.min((c + 1) * perCol, mcq);
            if (start > end) continue;
            
            colBlocks.push(\`
          block(
            stroke: (right: 0.5pt),
            inset: 2pt,
            [
              #grid(
                columns: (13pt, 12pt, 12pt, 12pt, 12pt),
                align(center)[#tracking-marker], align(center)[*A*], align(center)[*B*], align(center)[*C*], align(center)[*D*],
              )
              #v(2pt)
              #grid(columns: 1, row-gutter: 1.5pt, ..range(\${start}, \${end + 1}).map(i => grid(
                columns: (13pt, 12pt, 12pt, 12pt, 12pt),
                align(center + horizon)[*#i*],
                align(center + horizon, bubble("")),
                align(center + horizon, bubble("")),
                align(center + horizon, bubble("")),
                align(center + horizon, bubble("")),
              )))
            ]
          )\`);
        }
        
        mcqSection = \`
    #let info-phan1-box = block([
        #block(
          inset: (left: 4pt, right: 4pt, top: 2pt, bottom: 2pt),
          [
            #place(top + right, dx: 0pt, dy: -2pt)[#box(width: 1cm, height: 1cm, stroke: 0.5pt, fill: white)]
            #align(left)[#text(size: 10pt, weight: "bold")[PHIẾU TRẢ LỜI TRẮC NGHIỆM]]
            #v(2pt)
            Họ và tên: ..............................................................         #v(2pt)
            Lớp: .................... Môn: .................... Điểm: .......
          ],
        )
        #line(length: 100%, stroke: 0.8pt)
        #block(inset: (left: 4pt, right: 4pt, top: 2pt, bottom: 2pt), [ *PHẦN I - TRẮC NGHIỆM* ])
        #line(length: 100%, stroke: 0.8pt)
        #grid(columns: (1fr,) * \${cols}, \${colBlocks.join(',')} )
    ])\`;
    } else {
        mcqSection = \`#let info-phan1-box = block([])\`;
    }

    let tfSection = '';
    if (tf > 0) {
        let tfQs = [];
        for (let i=1; i<=tf; i++) {
            tfQs.push(\`grid(
        columns: (12pt, 14pt, 14pt),
        row-gutter: 1.5pt,
        grid.cell(rowspan: 2, align: center + horizon)[#tracking-marker],
        grid.cell(colspan: 2, align: center + bottom)[#text(size: 7pt, weight: "bold")[Câu \${i}]],
        align(center)[#text(size: 7pt, weight: "bold")[Đ]], align(center)[#text(size: 7pt, weight: "bold")[S]],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      )\`);
        }
        
        tfSection = \`
    #let phan2-box = block([
        #block(inset: 2pt, [ *PHẦN II - ĐÚNG/SAI* ])
        #line(length: 100%, stroke: 0.8pt)
        #block(
          inset: (top: 2pt, bottom: 2pt, left: 2pt, right: 2pt),
          grid(columns: (1fr, 1fr), gutter: 4pt, \${tfQs.join(', ')}),
        )
    ])\`;
    } else {
        tfSection = \`#let phan2-box = block([])\`;
    }

    let tlnSection = '';
    if (tln > 0) {
        let tlnQs = [];
        for(let num=1; num<=tln; num++) {
            tlnQs.push(\`block(
        stroke: (right: 0.5pt),
        width: 100%,
        [
          #block(
            inset: (top: 2pt, bottom: 2pt, left: 4pt),
            align(left)[#text(size:8pt)[*Câu \${num}*]]
          )
          #block(
            inset: 2pt,
            grid(
              columns: (12pt, 12pt, 12pt, 12pt, 12pt),
              align(center, tracking-marker),
              align(center, empty-box), align(center, empty-box), align(center, empty-box), align(center, empty-box),
            ),
          )
          #block(
            inset: (top: 2pt, bottom: 2pt, left: 1pt, right: 1pt),
            grid(
              columns: (12pt, 12pt, 12pt, 12pt, 12pt),
              row-gutter: 1pt,
              align(center)[-], align(center, bubble("")), [], [], [],
              align(center)[,], [], align(center, bubble("")), align(center, bubble("")), [],
              align(center)[*0*], [], align(center, bubble("")), align(center, bubble("")), align(center, bubble("")),
              ..range(1, 10).map(r => (
                align(center)[*#r*], align(center, bubble("")), align(center, bubble("")), align(center, bubble("")), align(center, bubble(""))
              )).flatten(),
            ),
          )
        ],
      )\`);
        }
        
        tlnSection = \`
    #block(
      stroke: 0.8pt + black,
      width: 100%,
      [
        #block(inset: 2pt, [*PHẦN III - TỰ LUẬN NGẮN*])
        #line(length: 100%, stroke: 0.8pt)
        #block(
          inset: (left: 10pt, right: 10pt),
          grid(
            columns: (1fr,) * \${tln},
            \${tlnQs.join(', ')}
          )
        )
      ],
    )\`;
    }

    const assemble = \`
    #block(
      width: 100%,
      stroke: 0.8pt + black,
      grid(
        columns: (auto, auto, 2.2fr, 1.2fr),
        sbd-box,
        block(stroke: (left: 0.8pt, right: 0.8pt), made-box),
        info-phan1-box,
        block(stroke: (left: 0.8pt), phan2-box)
      )
    )
    \${tlnSection}
  ]
]
\`;

    return macros + header + mcqSection + tfSection + assemble;
}`;

const modified = indexHtml.replace(regex, newFn);
if(modified === indexHtml) {
    console.error("NO CHANGE MADE! Regex didn't match.");
} else {
    fs.writeFileSync('index.html', modified);
    console.log("SUCCESS!");
}
