const fs = require('fs');
let html = fs.readFileSync('index.html', 'utf-8');

// The best way is to evaluate the genWasmTypst function from index.html
let match = html.match(/function genWasmTypst\([\s\S]*?\n\s*\/\/\s*Return/);
let body = match ? match[0] : "";
if (body) {
    // We need to inject the end bracket
    body = body.replace(/\/\/\s*Return.*/, 'return src;\n}');
    // Add missing parts
    let fullCode = `
        function getWasmHeader(isA5, title) {
            let marginStr = isA5 ? '(top: 5mm, bottom: 5mm, left: 6mm, right: 6mm)' : '(top: 8mm, bottom: 8mm, left: 10mm, right: 10mm)';
            return \`// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "\${isA5 ? 'a5' : 'a4'}",
  flipped: \${isA5 ? 'true' : 'false'},
  fill: white,
  margin: \${marginStr},
)
#set text(size: 8pt, font: "Times New Roman")

#let marker = box(fill: black, width: 12pt, height: 12pt)
#let tracking-marker = box(fill: black, width: 10pt, height: 10pt)

#let bubble(label) = {
  align(center + horizon)[
    #circle(
      radius: 4.5pt,
      stroke: 0.5pt + rgb("#333333"),
      fill: white,
      align(center + horizon)[#text(size: 6.5pt, fill: rgb("#cccccc"), font:"Arial")[#label]]
    )
  ]
}

#let empty-box = align(center + horizon)[#box(width: 10pt, height: 10pt)]
\`;
        }

        function getWasmHeaderInfo(title, isA5) {
            let widthStr = isA5 ? '100%' : '100%';
            let strokeStr = isA5 ? '0.5pt' : '0.8pt';
            let spacingStr = isA5 ? '4pt' : '10pt';
            return \`// ── HEADER ──────────────────────────────────────────────────
#grid(
  columns: (1fr, auto, 1fr),
  align: center + horizon,
  marker,
  align(center)[
    #text(size: 14pt, weight: "bold", fill: rgb("#d32f2f"))[\${title}]
  ],
  marker
)
#v(\${spacingStr})

// Thêm block bao quanh thông tin học sinh
#block(
  width: \${widthStr},
  stroke: (paint: rgb("#666666"), thickness: \${strokeStr}, dash: "dashed"),
  radius: 4pt,
  inset: 5pt,
  clip: true,
  [
    #grid(
      columns: (6fr, 4fr, 4fr),
      column-gutter: 10pt,
      align: left + horizon,
      [
        #text(size: 9pt, weight: "bold")[Họ và tên học sinh: ] ..............................................................
        #v(4pt)
        #text(size: 9pt, weight: "bold")[Lớp: ] ....................................................................................
      ],
      [
        #align(center)[#text(size: 9pt, weight: "bold")[Số Báo Danh]]
        #v(2pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt, 12pt, 12pt),
          align: center,
          tracking-marker, empty-box, empty-box, empty-box, empty-box, empty-box,
        )
        #v(1pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt, 12pt, 12pt),
          rows: (11pt,) * 10,
          align: center + horizon,
          ..range(0, 10).map(r => (
            [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble("0"), bubble("0"), bubble("0"), bubble("0"), bubble("0")
          )).flatten(),
        )
      ],
      [
        #align(center)[#text(size: 9pt, weight: "bold")[Mã đề thi]]
        #v(2pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt),
          align: center,
          tracking-marker, empty-box, empty-box, empty-box,
        )
        #v(1pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt),
          rows: (11pt,) * 10,
          align: center + horizon,
          ..range(0, 10).map(r => (
            [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble("0"), bubble("0"), bubble("0")
          )).flatten(),
        )
      ]
    )
  ]
)
\`;
        }

    \${body}
    
    // Evaluate ds20-tln10-ngang
    // For this, we just need to pass 0 MCQ, 20 TF, 10 TLN, and type='ds20-tln10-ngang'
    let src = genWasmTypst(0, 20, 10, 'ds20-tln10-ngang');
    fs.writeFileSync('templates/ds20-tln10-ngang.typ', src);
    console.log("Success");
    `;
    fs.writeFileSync('eval_gen.cjs', fullCode);
} else {
    console.log("NOT FOUND");
}
