import re

html = open('index.html', 'r', encoding='utf-8').read()

# Replace buildTypstCode entirely
old_func_start = html.find('function buildTypstCode(mcq, tf, tln, paper) {')
old_func_end = html.find('// ── Bulk Gen', old_func_start)
if old_func_end == -1:
    old_func_end = html.find('function generateSheetCmd() {', old_func_start)

new_func = """function buildTypstCode(mcq, tf, tln, paper) {
  const school = document.getElementById('genSchool')?.value || 'SANG MATH OMR';
  const subtitle = document.getElementById('genSubtitle')?.value || 'Custom Template';
  const handwritten = document.getElementById('bldHandwritten')?.checked ?? true;
  return genWasmTypst({ mcq, tf, tln, paper, school, subtitle, handwritten, realQr: true });
}
"""

html = html[:old_func_start] + new_func + '\n' + html[old_func_end:]

# Update genWasmTypst to support realQr
# Find: #rect(fill: luma(220), width: 24pt, height: 24pt, stroke: none)[
#             #align(center+horizon)[#text(5pt, fill: luma(100))[QR]]
#           ]
old_qr = """          #rect(fill: luma(220), width: 24pt, height: 24pt, stroke: none)[
            #align(center+horizon)[#text(5pt, fill: luma(100))[QR]]
          ]"""
new_qr = """          ${realQr ? `#qr-code("OMR: SANG MATH|Mã đề", width: 24pt)` : `#rect(fill: luma(220), width: 24pt, height: 24pt, stroke: none)[
            #align(center+horizon)[#text(5pt, fill: luma(100))[QR]]
          ]`}"""
html = html.replace(old_qr, new_qr)

# Add realQr to params
html = html.replace('function genWasmTypst({ mcq, tf, tln, paper, school, subtitle, handwritten }) {', 'function genWasmTypst({ mcq, tf, tln, paper, school, subtitle, handwritten, realQr }) {')

# Prepend #import if realQr
import_qr = """  return `${realQr ? '#import "@preview/cades:0.3.1": qr-code\\n' : ''}// Preview-safe Typst – no external packages
// Generated by Sang Math OMR"""
html = html.replace('  return `// Preview-safe Typst – no external packages\n// Generated by Sang Math OMR', import_qr)

# Fix downloadTypFile to download actual typst code instead of bash script
# Because downloading bash script as .typ is a bug.
# Let's leave downloadTypFile as is if they meant it to be a bash script?
# No, "Tải Script .sh" is downloadGenScript(). "Tải file .typ" is downloadTypFile().
# Clearly they meant to download the template file!
# I will change downloadTypFile to download the currently selected template using buildTypstCode!

download_typ_fix = """function downloadTypFile() {
  const mcq = parseInt(document.getElementById('bldMcq').value) || 0;
  const tf  = parseInt(document.getElementById('bldTf').value)  || 0;
  const tln = parseInt(document.getElementById('bldTln').value) || 0;
  const paper = document.querySelector('input[name="bldPaper"]:checked')?.value || 'a4';
  const code = buildTypstCode(mcq, tf, tln, paper);
  const blob = new Blob([code], {type:'text/plain'});
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `phieu_omr_${selectedTemplateType}.typ`;
  a.click();
}"""

html = re.sub(r'function downloadTypFile\(\)\s*\{[\s\S]*?a\.click\(\);\s*\}', download_typ_fix, html)


open('index.html', 'w', encoding='utf-8').write(html)
