const fs = require('fs');

function getWasmHeader(isA5, title) {
    let marginStr = isA5 ? '(top: 5mm, bottom: 5mm, left: 6mm, right: 6mm)' : '(top: 8mm, bottom: 8mm, left: 10mm, right: 10mm)';
    return `// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "${isA5 ? 'a5' : 'a4'}",
  flipped: ${isA5 ? 'true' : 'false'},
  fill: white,
  margin: ${marginStr},
)
#set text(size: 8pt, font: "Times New Roman")

#let marker = box(fill: black, width: 12pt, height: 12pt)
#let tracking-marker = box(fill: black, width: 10pt, height: 10pt)

#let bubble(label) = {
  align(center + horizon)[
    #circle(
      radius: 4.5pt,
      stroke: 0.5pt + rgb("#333333"),
      fill: white,
      align(center + horizon)[#text(size: 6.5pt, weight: "regular", fill: rgb("#888888"))[#label]]
    )
  ]
}
#let empty-box = box(stroke: 0.8pt + black, width: if ${isA5} { 10pt } else { 11pt }, height: if ${isA5} { 10pt } else { 11pt })
#let qb = box(width: 1.8pt, height: 1.8pt, fill: black)
#let qw = box(width: 1.8pt, height: 1.8pt, fill: white)

#place(top + left, dx: -2mm, dy: -2mm, marker)
#place(top + right, dx: 2mm, dy: -2mm, marker)
#place(bottom + left, dx: -2mm, dy: 2mm, marker)
#place(bottom + right, dx: 2mm, dy: 2mm, marker)
#align(top + center)[
  #scale(x: if ${isA5} { 88% } else { 95% }, y: if ${isA5} { 88% } else { 95% }, origin: top)[
    #block(width: 100%, height: 0pt)[
      #place(left, dx: if ${isA5} { 35mm } else { 43mm }, dy: 15mm)[
        #grid(columns: 21, column-gutter: 0pt, row-gutter: 0pt,
  qb, qb, qb, qb, qb, qb, qb, qw, qw, qb, qw, qb, qb, qw, qb, qb, qb, qb, qb, qb, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qb, qw, qw, qb, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw, qb, qw, qw, qb, qw, qb, qb, qb, qw, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qb, qw, qb, qw, qb, qb, qb, qb, qb, qb, qb,
  qw, qw, qw, qw, qw, qw, qw, qw, qb, qw, qw, qb, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qb, qb, qb, qb, qb, qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qb, qb, qb, qw,
  qb, qw, qb, qw, qw, qb, qw, qb, qw, qb, qb, qb, qb, qw, qb, qw, qw, qw, qw, qw, qb,
  qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw, qw, qw, qw, qb, qb, qw, qb, qw,
  qb, qb, qb, qw, qw, qw, qb, qw, qw, qb, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qb,
  qw, qw, qw, qw, qw, qw, qw, qw, qb, qb, qw, qw, qw, qw, qb, qw, qw, qb, qb, qw, qw,
  qb, qb, qb, qb, qb, qb, qb, qw, qw, qw, qw, qb, qb, qb, qb, qb, qw, qb, qb, qb, qb,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qb, qw, qw, qb, qw, qw, qb, qb, qb, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qb, qb, qw, qb, qw, qw, qw, qw, qw, qw, qw,
  qb, qw, qb, qb, qb, qw, qb, qw, qb, qw, qw, qb, qw, qw, qw, qw, qb, qb, qw, qb, qb,
  qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qw, qb, qw, qb, qw, qb, qb, qw, qw, qw,
  qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qb, qw, qb, qw, qw, qb, qb, qw, qb, qb,
  qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qw, qw, qb, qw, qw, qb, qw,
        )
      ]
    ]
`;
}

function getWasmHeaderInfo(title, isA5) {
    let widthStr = isA5 ? '100%' : '100%';
    let strokeStr = isA5 ? '0.5pt' : '0.8pt';
    let spacingStr = isA5 ? '4pt' : '10pt';
    return `// ── HEADER ──────────────────────────────────────────────────
#grid(
  columns: (1fr, auto, 1fr),
  align: center + horizon,
  none,
  align(center)[
    #text(size: 14pt, weight: "bold", fill: rgb("#d32f2f"))[${title}]
  ],
  none
)
#v(${spacingStr})

// Thêm block bao quanh thông tin học sinh
#block(
  width: ${widthStr},
  stroke: (paint: rgb("#666666"), thickness: ${strokeStr}, dash: "dashed"),
  radius: 4pt,
  inset: 5pt,
  clip: true,
  [
    #grid(
      columns: (6fr, 4fr, 4fr),
      column-gutter: 10pt,
      align: left + horizon,
      [
        #text(size: 9pt, weight: "bold")[Họ và tên học sinh: ] ..............................................................
        #v(4pt)
        #text(size: 9pt, weight: "bold")[Lớp: ] ....................................................................................
      ],
      [
        #align(center)[#text(size: 9pt, weight: "bold")[Số Báo Danh]]
        #v(2pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt, 12pt, 12pt),
          align: center,
          tracking-marker, empty-box, empty-box, empty-box, empty-box, empty-box,
        )
        #v(1pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt, 12pt, 12pt),
          rows: (11pt,) * 10,
          align: center + horizon,
          ..range(0, 10).map(r => (
            [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble("0"), bubble("0"), bubble("0"), bubble("0"), bubble("0")
          )).flatten(),
        )
      ],
      [
        #align(center)[#text(size: 9pt, weight: "bold")[Mã đề thi]]
        #v(2pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt),
          align: center,
          tracking-marker, empty-box, empty-box, empty-box,
        )
        #v(1pt)
        #grid(
          columns: (12pt, 12pt, 12pt, 12pt),
          rows: (11pt,) * 10,
          align: center + horizon,
          ..range(0, 10).map(r => (
            [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble("0"), bubble("0"), bubble("0")
          )).flatten(),
        )
      ]
    )
  ]
)
`;
}

function genWasmTypst(mcq, tf, tln, type) {
    const isA5 = type.includes('ngang');
    let title = "PHIẾU TRẢ LỜI TRẮC NGHIỆM";
    if (type === 'thptqg-toan') {
        title = "PHIẾU TRẢ LỜI TRẮC NGHIỆM THPTQG MÔN TOÁN 2025";
    }

    let src = getWasmHeader(isA5, title) + '\n' + getWasmHeaderInfo(title, isA5);

    if (mcq > 0) {
        let cols = isA5 ? 5 : 4;
        src += `// ── PHẦN TRẮC NGHIỆM ───────────────────────────────────────
#v(if ${isA5} { -2pt } else { 4pt })
#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN I – TRẮC NGHIỆM (${mcq} câu, mỗi câu 4 đáp án A/B/C/D)]]])
  #block(
    inset: (top: 8pt, bottom: 8pt, left: 10pt, right: 10pt),
    grid(
      columns: (1fr,) * ${cols},
      row-gutter: 6pt,
      column-gutter: 8pt,
`;
        for (let i = 1; i <= mcq; i++) {
            src += `      grid(
        columns: (15pt, 12pt, 12pt, 12pt, 12pt),
        row-gutter: 4pt,
        align: center + horizon,
        grid.cell(align: left + horizon)[#text(size:8pt)[*${i}*]],
        tracking-marker, bubble("A"), bubble("B"), bubble("C"), bubble("D")
      ),\n`;
        }
        src += `    )\n  )\n])\n`;
    }

    if (tf > 0) {
        let cols = isA5 ? 5 : 4;
        let totalQuestions = tf;
        src += `// ── PHẦN ĐÚNG/SAI ──────────────────────────────────────────
#v(if ${isA5} { -2pt } else { 4pt })
#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN II – ĐÚNG / SAI (${tf} câu, mỗi câu 4 ý a/b/c/d)]]])
  #block(
    inset: (top: 8pt, bottom: 8pt, left: 10pt, right: 10pt),
    grid(
      columns: (1fr,) * ${cols},
      row-gutter: 4pt,
      column-gutter: 8pt,
`;
        
        let qPerCol = Math.ceil(totalQuestions / cols);
        let columnsData = Array.from({length: cols}, () => []);
        for (let i = 0; i < totalQuestions; i++) {
            columnsData[Math.floor(i / qPerCol)].push(i + 1);
        }

        let sortedQuestions = [];
        for (let r = 0; r < qPerCol; r++) {
            for (let c = 0; c < cols; c++) {
                if (columnsData[c] && columnsData[c][r]) {
                    sortedQuestions.push(columnsData[c][r]);
                }
            }
        }

        for (let i of sortedQuestions) {
            src += `      grid(
        columns: (15pt, 16pt, 16pt),
        row-gutter: 2.5pt,
        column-gutter: 3pt,
        align: center + horizon,
        grid.cell(colspan: 3, align: left + horizon)[
          #stack(dir: ltr, spacing: 4pt,
            tracking-marker,
            text(size: 8pt, weight: "bold")[Câu ${i}]
          )
        ],
        none, text(size: 7.5pt, weight: "bold")[Đ], text(size: 7.5pt, weight: "bold")[S],
        [a)], bubble(""), bubble(""),
        [b)], bubble(""), bubble(""),
        [c)], bubble(""), bubble(""),
        [d)], bubble(""), bubble(""),
      ),\n`;
        }
        src += `    )\n  )\n])\n`;
    }

    if (tln > 0) {
        let cols = isA5 ? 5 : 5;
        let scale = isA5 ? 0.75 : 1;
        let totalQuestions = tln;
        src += `// ── PHẦN TỰ LUẬN NGẮN ──────────────────────────────────────
#v(if ${isA5} { -2pt } else { 4pt })
#scale(x: ${scale * 100}%, y: ${scale * 100}%, origin: top + left)[
#block(width:${100/scale}%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN III – TỰ LUẬN NGẮN (Câu 1-${tln})]]])
  #block(
    inset: (left: 10pt, right: 10pt, top: if ${isA5} { 3pt } else { 0pt }, bottom: if ${isA5} { 5pt } else { 6pt }),
    grid(
      columns: (1fr,) * ${cols},
      row-gutter: 4pt,
`;
        
        let qPerCol = Math.ceil(totalQuestions / cols);
        let columnsData = Array.from({length: cols}, () => []);
        for (let i = 0; i < totalQuestions; i++) {
            columnsData[Math.floor(i / qPerCol)].push(i + 1);
        }

        let sortedQuestions = [];
        for (let r = 0; r < qPerCol; r++) {
            for (let c = 0; c < cols; c++) {
                if (columnsData[c] && columnsData[c][r]) {
                    sortedQuestions.push(columnsData[c][r]);
                }
            }
        }

        for (let i of sortedQuestions) {
            src += `      block(
        stroke: (right: 0.5pt),
        width: 100%,
        inset: (bottom: if ${isA5} { 2pt } else { 4pt }),
        [
          #align(left)[#text(size:8pt)[*Câu ${i}*]]
          #v(if ${isA5} { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            align: center + horizon,
            tracking-marker,
            empty-box, empty-box, empty-box, empty-box,
          )
          #v(if ${isA5} { 1pt } else { 2pt })
          #grid(
            columns: (12pt, 12pt, 12pt, 12pt, 12pt),
            rows: (if ${isA5} { 9.8pt } else { 12.5pt },) * 13,
            align: center + horizon,
            [#text(size: 6.5pt, fill: rgb("#666666"))[-]], bubble(""), [], [], [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[,]], [], bubble(""), bubble(""), [],
            [#text(size: 6.5pt, fill: rgb("#666666"))[0]], bubble(""), bubble(""), bubble(""), bubble(""),
            ..range(1, 10).map(r => (
              [#text(size: 6.5pt, fill: rgb("#666666"))[#r]], bubble(""), bubble(""), bubble(""), bubble("")
            )).flatten(),
          )
        ]
      ), `;
        }
        src += `    )\n  )\n])\n]`;
    }

    src += `\n// ── TỰ LUẬN VIẾT TAY ────────────────────────────────────────\n\n\n  ]\n]\n`;
    return src;
}

// Generate ds20-tln10-ngang
const src = genWasmTypst(0, 20, 10, 'ds20-tln10-ngang');
fs.writeFileSync('templates/ds20-tln10-ngang.typ', src);
fs.writeFileSync('templates/tln-10-ngang.typ', genWasmTypst(0, 0, 10, 'tln-10-ngang'));
console.log("Done");
