import sys

content = """#let ln-nguluc-note-for(ch) = {
"""

stories = [
  # 1 Học Nhi
  "  *Tử viết:* Học nhi thời tập chi, bất diệc duyệt hồ? Hữu bằng tự viễn phương lai, bất diệc lạc hồ? Nhân bất tri nhi bất uấn, bất diệc quân tử hồ?\n  _(Khổng Tử nói: Học mà thường xuyên ôn tập, chẳng phải vui sao? Có bạn từ phương xa đến, chẳng phải mừng sao? Người đời không biết đến mình mà mình không oán giận, chẳng phải là người quân tử sao?)_\n\n  *Hữu Tử viết:* Kỳ vi nhân dã hiếu đệ, nhi hiếu phạm thượng giả, tiễn hĩ... Bổn lập nhi đạo sinh.\n  _(Hữu Tử nói: Người hiếu thảo với cha mẹ, nhường nhịn anh em mà lại thích phạm thượng là rất hiếm... Gốc có vững thì đạo làm người mới sinh ra.)_",
  # 2 Vi Chính
  "  *Tử viết:* Vi chính dĩ đức, thí như Bắc thần, cư kỳ sở nhi chúng tinh củng chi.\n  _(Khổng Tử nói: Dùng đức để trị dân, giống như sao Bắc Đẩu, đứng yên một chỗ mà các vì sao khác đều chầu về.)_\n\n  *Tử viết:* Ngô thập hữu ngũ nhi chí vu học, tam thập nhi lập, tứ thập nhi bất hoặc, ngũ thập nhi tri thiên mệnh...\n  _(Khổng Tử nói: Ta mười lăm tuổi dốc chí vào việc học, ba mươi tuổi lập thân, bốn mươi tuổi không còn nghi ngờ, năm mươi tuổi biết mệnh trời...)_\n\n  *Tử viết:* Ôn cố nhi tri tân, khả dĩ vi sư hĩ.\n  _(Khổng Tử nói: Ôn lại cái cũ mà biết được cái mới, có thể làm thầy người khác được rồi.)_",
  # 3 Bát Dật
  "  *Tử viết:* Nhân nhi bất nhân, như lễ hà? Nhân nhi bất nhân, như nhạc hà?\n  _(Khổng Tử nói: Người mà không có lòng nhân, thì Lễ để làm gì? Người mà không có lòng nhân, thì Nhạc để làm gì?)_\n\n  *Lâm Phóng vấn lễ chi bản. Tử viết:* Đại tai vấn! Lễ, dữ kỳ xa dã, ninh kiệm; tang, dữ kỳ dị dã, ninh thích.\n  _(Lâm Phóng hỏi về gốc của Lễ. Khổng Tử nói: Hỏi hay lắm! Lễ, thà chuộng sự tiết kiệm còn hơn xa hoa; Tang lễ, thà thật lòng thương xót còn hơn hình thức rườm rà.)_",
  # 4 Lý Nhân
  "  *Tử viết:* Lý nhân vi mỹ. Trạch bất xử nhân, yên đắc trí?\n  _(Khổng Tử nói: Chọn nơi có phong tục nhân hậu để ở là đẹp. Chọn chỗ ở mà không chọn nơi nhân đức, sao gọi là khôn ngoan?)_\n\n  *Tử viết:* Quân tử dụ ư nghĩa, tiểu nhân dụ ư lợi.\n  _(Khổng Tử nói: Người quân tử am hiểu và hành động vì nghĩa, kẻ tiểu nhân am hiểu và hành động vì lợi.)_\n\n  *Tử viết:* Kiến hiền tư tề yên, kiến bất hiền nhi nội tự tỉnh dã.\n  _(Khổng Tử nói: Thấy người hiền thì phải suy nghĩ làm sao cho bằng họ, thấy người không hiền thì phải tự xét lại mình.)_",
  # 5 Công Dã Tràng
  "  *Tử viết:* Thính kỳ ngôn nhi quan kỳ hành.\n  _(Khổng Tử nói: Nghe lời người ta nói, còn phải xem việc người ta làm.)_\n\n  *Tử Cống vấn viết:* Khổng Văn tử hà dĩ vị chi 'Văn' dã? *Tử viết:* Mẫn nhi hiếu học, bất sỉ hạ vấn, thị dĩ vị chi 'Văn' dã.\n  _(Tử Cống hỏi: Tại sao Khổng Văn Tử được ban thụy hiệu là 'Văn'? Khổng Tử nói: Thông minh lại ham học, không xấu hổ khi hỏi kẻ dưới mình, nên được gọi là 'Văn'.)_",
  # 6 Ung Dã
  "  *Tử viết:* Hiền tai Hồi dã! Nhất đan thực, nhất biều ẩm, tại lậu hạng, nhân bất kham kỳ ưu, Hồi dã bất cải kỳ lạc. Hiền tai Hồi dã!\n  _(Khổng Tử nói: Hiền thay Nhan Hồi! Một giỏ cơm, một bầu nước, ở ngõ hẻm nghèo nàn, người ta không chịu nổi sự ưu sầu, thế mà Hồi không thay đổi niềm vui. Hiền thay Nhan Hồi!)_\n\n  *Tử viết:* Chất thắng văn tắc dã, văn thắng chất tắc sử. Văn chất bân bân, nhiên hậu quân tử.\n  _(Khổng Tử nói: Chất phác mà thắng văn vẻ thì thô kệch, văn vẻ mà thắng chất phác thì hào nhoáng. Văn và chất hòa hợp đều nhau, sau mới là người quân tử.)_",
  # 7 Thuật Nhi
  "  *Tử viết:* Thuật nhi bất tác, tín nhi hiếu cổ.\n  _(Khổng Tử nói: Ta chỉ thuật lại chứ không sáng tác, tin tưởng và yêu chuộng văn hóa cổ xưa.)_\n\n  *Tử viết:* Tam nhân hành, tất hữu ngã sư yên. Trạch kỳ thiện giả nhi tòng chi, kỳ bất thiện giả nhi cải chi.\n  _(Khổng Tử nói: Ba người cùng đi, ắt có người là thầy ta. Chọn cái tốt của họ mà theo, thấy cái xấu của họ mà tự sửa mình.)_\n\n  *Tử viết:* Bất phẫn bất khải, bất phỉ bất phát. Cử nhất ngung nhi bất dĩ tam ngung phản, tắc bất phục dã.\n  _(Khổng Tử nói: Học trò không bức xúc muốn biết thì ta không gợi mở, không cố gắng diễn đạt thì ta không chỉ bảo. Đưa cho một góc mà không biết suy ra ba góc kia, thì ta không dạy tiếp nữa.)_",
  # 8 Thái Bá
  "  *Tử viết:* Đốc tín hiếu học, thủ tử thiện đạo. Nguy bang bất nhập, loạn bang bất cư.\n  _(Khổng Tử nói: Có niềm tin vững chắc và ham học, giữ cho đến chết con đường đạo đức tốt đẹp. Nước nguy ngập thì không vào, nước loạn lạc thì không ở.)_\n\n  *Tử viết:* Học như bất cập, do khủng thất chi.\n  _(Khổng Tử nói: Học như kẻ đuổi theo không kịp, lại còn lo sợ những gì đã học sẽ mất đi.)_",
  # 9 Tử Hãn
  "  *Tử tại xuyên thượng viết:* Thệ giả như tư phu! Bất xá trú dạ.\n  _(Khổng Tử đứng trên bờ sông nói: Nước trôi đi như thế này sao! Ngày đêm không ngừng nghỉ.)_\n\n  *Tử viết:* Tuế hàn, nhiên hậu tri tùng bách chi hậu điêu dã.\n  _(Khổng Tử nói: Năm tháng giá lạnh, sau đó mới biết cây tùng cây bách rụng lá muộn.)_\n\n  *Tử viết:* Tam quân khả đoạt soái dã, thất phu bất khả đoạt chí dã.\n  _(Khổng Tử nói: Ba quân có thể đoạt mất chủ tướng, nhưng một người thất phu thì không thể bị đoạt mất ý chí.)_",
  # 10 Hương Đảng
  "  *Khổng Tử ư hương đảng,* luân luân như dã, tự bất năng ngôn giả. Kỳ tại tông miếu triều đình, tiện tiện ngôn, duy cẩn nhĩ.\n  _(Khổng Tử ở quê nhà, bộ điệu khiêm cung, như người không biết ăn nói. Nhưng ở chốn miếu đường triều đình, ngài nói năng lưu loát, chỉ là rất cẩn trọng.)_\n\n  *Thực bất yếm tinh,* quái bất yếm tế. Cắt bất chính, bất thực.\n  _(Ăn gạo không chê giã trắng, thái thịt không chê thái mỏng. Cắt không vuông vức, không ăn. Thể hiện sự tinh tế và kỷ luật trong đời sống thường ngày.)_",
  # 11 Tiên Tiến
  "  *Tử viết:* Hồi dã kỳ thứ hồ, lũ không. Tứ bất thụ mệnh nhi thực hóa, ức tắc lũ trúng.\n  _(Khổng Tử nói: Nhan Hồi học đạo đã gần đến mức hoàn thiện rồi, thường phải chịu cảnh bĩ cực trống rỗng. Tử Cống không an phận mệnh trời mà đi buôn bán sinh lời, phỏng đoán điều gì thường trúng điều đó.)_\n\n  *Tử Cống vấn:* Sư dữ Thương dã thục hiền? *Tử viết:* Sư dã quá, Thương dã bất cập... Quá do bất cập.\n  _(Tử Cống hỏi: Tử Trương và Tử Hạ ai giỏi hơn? Khổng Tử đáp: Tử Trương thì làm quá mức, Tử Hạ thì làm không tới... Thái quá cũng như bất cập.)_",
  # 12 Nhan Uyên
  "  *Nhan Uyên vấn nhân. Tử viết:* Khắc kỷ phục lễ vi nhân. Nhất nhật khắc kỷ phục lễ, thiên hạ quy nhân yên.\n  _(Nhan Uyên hỏi về điều Nhân. Khổng Tử nói: Khắc chế bản thân, quay về với Lễ là Nhân. Một ngày làm được vậy, thiên hạ sẽ theo về với điều Nhân.)_\n\n  *Tử viết:* Kỷ sở bất dục, vật thi ư nhân.\n  _(Khổng Tử nói: Điều gì mình không muốn thì đừng làm cho người khác.)_\n\n  *Tử viết:* Quân tử thành nhân chi mỹ, bất thành nhân chi ác. Tiểu nhân phản thị.\n  _(Khổng Tử nói: Người quân tử thành tựu cái tốt cho người, không hùa theo cái xấu của người. Kẻ tiểu nhân thì làm ngược lại.)_",
  # 13 Tử Lộ
  "  *Tử Lộ vấn chính. Tử viết:* Tiên chi, lao chi.\n  _(Tử Lộ hỏi về chính sự. Khổng Tử đáp: Phải làm gương đi đầu trước dân, sau đó mới khuyến khích dân làm lụng.)_\n\n  *Tử viết:* Kỳ thân chính, bất lệnh nhi hành; kỳ thân bất chính, tuy lệnh bất tòng.\n  _(Khổng Tử nói: Bản thân người lãnh đạo mà ngay thẳng, không ra lệnh người ta cũng làm theo; bản thân mà không ngay thẳng, có ra lệnh cũng không ai theo.)_\n\n  *Tử viết:* Vô dục tốc, vô kiến tiểu lợi. Dục tốc tắc bất đạt, kiến tiểu lợi tắc đại sự bất thành.\n  _(Khổng Tử nói: Đừng muốn mau chóng, đừng nhìn lợi nhỏ. Muốn mau chóng thì không đạt, nhìn lợi nhỏ thì việc lớn không thành.)_",
  # 14 Hiến Vấn
  "  *Hoặc viết:* Dĩ đức báo oán, hà như? *Tử viết:* Hà dĩ báo đức? Dĩ trực báo oán, dĩ đức báo đức.\n  _(Có người hỏi: Lấy đức báo oán, ngài thấy sao? Khổng Tử nói: Thế lấy gì để báo đức? Hãy lấy sự ngay thẳng (công lý) để báo oán, và lấy ân đức để báo ân đức.)_\n\n  *Tử viết:* Quân tử sỉ kỳ ngôn nhi quá kỳ hành.\n  _(Khổng Tử nói: Người quân tử thấy hổ thẹn nếu lời nói của mình vượt quá việc làm thực tế.)_",
  # 15 Vệ Linh Công
  "  *Tử Cống vấn viết:* Hữu nhất ngôn nhi khả dĩ chung thân hành chi giả hồ? *Tử viết:* Kỳ thứ hồ! Kỷ sở bất dục, vật thi ư nhân.\n  _(Tử Cống hỏi: Có một chữ nào có thể giữ làm tiêu chuẩn tu hành suốt đời không? Khổng Tử đáp: Có lẽ là chữ 'Thứ' chăng? Điều gì mình không muốn thì đừng làm cho người khác.)_\n\n  *Tử viết:* Ngô đạo nhất dĩ quán chi.\n  _(Khổng Tử nói: Đạo của ta chỉ dùng một mối mà xâu chuỗi tất cả.)_\n\n  *Tử viết:* Quá nhi bất cải, thị vị quá hĩ.\n  _(Khổng Tử nói: Có lỗi lầm mà không chịu sửa, đó mới thực sự là lỗi lầm.)_",
  # 16 Quý Thị
  "  *Khổng Tử viết:* Hữu ích giả tam hữu, hữu tổn giả tam hữu. Hữu trực, hữu lượng, hữu đa văn, ích hĩ. Hữu tiện tích, hữu thiện nhu, hữu tiện nịnh, tổn hĩ.\n  _(Khổng Tử nói: Kết bạn có ba hạng có ích, ba hạng có hại. Bạn ngay thẳng, bạn chân thành rộng lượng, bạn hiểu biết nhiều, là có ích. Bạn xiểm nịnh a dua, bạn khéo chiều chuộng bề ngoài, bạn dẻo miệng nói hay, là có hại.)_\n\n  *Khổng Tử viết:* Bất hoạn quả nhi hoạn bất quân, bất hoạn bần nhi hoạn bất an.\n  _(Khổng Tử nói: Không lo dân ít mà lo chia không đều, không lo dân nghèo mà lo lòng người không an.)_",
  # 17 Dương Hóa
  "  *Tử viết:* Tính tương cận dã, tập tương viễn dã.\n  _(Khổng Tử nói: Bản tính con người lúc sinh ra vốn gần giống nhau, nhưng do thói quen huân tập trong đời sống mà trở nên xa cách nhau.)_\n\n  *Tử chi Vũ Thành,* văn huyền ca chi thanh. Phu tử oản nhĩ nhi tiếu viết: Cát kê yên dụng ngưu đao?\n  _(Khổng Tử đến ấp Vũ Thành, nghe tiếng đàn hát. Phu tử mỉm cười nói: Giết con gà sao lại phải dùng đến dao mổ trâu?)_",
  # 18 Vi Tử
  "  *Sở cuồng Tiếp Dư ca nhi quá Khổng Tử viết:* Phượng hề! Phượng hề! Hà đức chi suy? Vãng giả bất khả gián, lai giả do khả truy. Dĩ nhi! Dĩ nhi! Kim chi tòng chính giả đãi nhi!\n  _(Tiếp Dư, người cuồng nước Sở, hát khi đi ngang qua Khổng Tử: Phượng hoàng ơi! Phượng hoàng ơi! Sao đức nhà ngươi nay suy đồi thế? Việc đã qua không thể can ngăn, việc sắp tới vẫn còn có thể đuổi kịp. Thôi đi! Thôi đi! Kẻ làm chính trị ngày nay nguy hiểm lắm rồi!)_",
  # 19 Tử Trương
  "  *Tử Cống viết:* Quân tử chi quá dã, như nhật nguyệt chi thực yên: quá dã, nhân giai kiến chi; canh dã, nhân giai ngưỡng chi.\n  _(Tử Cống nói: Lỗi lầm của người quân tử giống như hiện tượng nhật thực, nguyệt thực: khi có lỗi, mọi người đều nhìn thấy rõ; nhưng khi sửa đổi, mọi người đều ngưỡng vọng nể phục.)_\n\n  *Tử Hạ viết:* Bách công cư tứ dĩ thành kỳ sự, quân tử học dĩ trí kỳ đạo.\n  _(Tử Hạ nói: Trăm thợ ở trong xưởng để hoàn thành công việc của mình; người quân tử học tập để đạt đến tận cùng đạo lý của mình.)_",
  # 20 Nghiêu Viết
  "  *Tử viết:* Bất tri mệnh, vô dĩ vi quân tử dã. Bất tri lễ, vô dĩ lập dã. Bất tri ngôn, vô dĩ tri nhân dã.\n  _(Khổng Tử nói: Không biết Mệnh trời thì không có cách nào làm người quân tử. Không biết Lễ thì không có chỗ đứng trong xã hội. Không hiểu lời nói thì không thể thấu hiểu con người.)_",
]

for i, s in enumerate(stories, 1):
    content += f"  if ch == {i} [\n{s}\n  ] else "

content += "{\n    none\n  }\n}\n"

with open("/Users/admin/conictypst/typst/sach/luan-ngu/nguluc.typ", "w") as f:
    f.write(content)
