/*
 * SANG MATH OMR profile registry
 *
 * A profile is the shared contract between sheet generation, QR discovery,
 * answer filling and grading. Custom profiles carry only a compact descriptor
 * in the QR; calibrated bubble coordinates are recreated from the same Typst
 * layout and cached locally.
 */
(function () {
  'use strict';

  const QR_PREFIX = 'SMOMR:3:';
  const LEGACY_QR_PREFIX = 'SMOMR:2:';
  const STORAGE_KEY = 'smomr_profile_templates_v2';

  const BUILT_INS = {
    'a3-cat-phach': { id: 'a3-cat-phach', name: 'A3 Cắt Phách', mcq: 12, tf: 2, tln: 4, paper: 'a3', version: 2 },
    '12-4-6ngang': { id: '12-4-6ngang', name: 'Toán 12-4-6 · A4 ngang', mcq: 12, tf: 4, tln: 6, paper: 'a5', version: 2 },
    'thptqg-toan': { id: 'thptqg-toan', name: 'THPTQG Toán · A4 dọc', mcq: 12, tf: 4, tln: 6, paper: 'a4', version: 2 },
    'tn-40': { id: 'tn-40', name: 'TN-40', mcq: 40, tf: 0, tln: 0, paper: 'a4', version: 2 },
    'tn-50': { id: 'tn-50', name: 'TN-50', mcq: 50, tf: 0, tln: 0, paper: 'a4', version: 2 },
    'tn-60': { id: 'tn-60', name: 'TN-60', mcq: 60, tf: 0, tln: 0, paper: 'a4', version: 2 },
    'ds-12': { id: 'ds-12', name: 'ĐS-12', mcq: 0, tf: 12, tln: 0, paper: 'a4', version: 2 },
    'ds-20-ngang': { id: 'ds-20-ngang', name: 'ĐS-20 · A5 ngang', mcq: 0, tf: 20, tln: 0, paper: 'a5', version: 2 },
    'tln-10': { id: 'tln-10', name: 'TLN-10 · A4 dọc', mcq: 0, tf: 0, tln: 10, paper: 'a4', version: 2 },
    'tln-10-ngang': { id: 'tln-10-ngang', name: 'TLN-10 · A4 hai hàng', mcq: 0, tf: 0, tln: 10, paper: 'a4', version: 2, dynamic: true }
  };

  function clampInt(value, min, max) {
    const parsed = Number.parseInt(value, 10);
    if (!Number.isFinite(parsed)) return min;
    return Math.max(min, Math.min(max, parsed));
  }

  function customDescriptor(mcq, tf, tln, paper, compact = false) {
    const safe = {
      mcq: clampInt(mcq, 0, 100),
      tf: clampInt(tf, 0, 20),
      tln: clampInt(tln, 0, 20),
      paper: paper === 'a5' ? 'a5' : 'a4'
    };
    return {
      id: `custom-${safe.mcq}-${safe.tf}-${safe.tln}-${safe.paper}-${compact ? 'compact-' : ''}v3`,
      name: `Tùy chỉnh ${safe.mcq}TN · ${safe.tf}ĐS · ${safe.tln}TLN${compact ? ' · Gọn' : ''}`,
      ...safe,
      version: 3,
      compact: Boolean(compact),
      custom: true,
      dynamic: true
    };
  }

  function fromType(type, fallback) {
    if (type === 'custom') {
      return customDescriptor(fallback?.mcq, fallback?.tf, fallback?.tln, fallback?.paper, fallback?.compact);
    }
    // A sheet without the handwriting area moves the two lower markers up to
    // the real end of the OMR content. Give it its own QR/profile so it can
    // never be graded with coordinates from the full-page variant.
    if (BUILT_INS[type] && fallback?.compact) {
      const base = BUILT_INS[type];
      const descriptor = customDescriptor(base.mcq, base.tf, base.tln, base.paper, true);
      descriptor.name = `${base.name} · Gọn`;
      descriptor.baseId = type;
      return descriptor;
    }
    if (BUILT_INS[type]) return { ...BUILT_INS[type] };
    if (fallback) {
      return { id: type, name: type, version: 2, dynamic: true, ...fallback };
    }
    return null;
  }

  function get(type) {
    if (BUILT_INS[type]) return { ...BUILT_INS[type] };
    const cached = loadCache()[type];
    return cached?.descriptor ? { ...cached.descriptor } : null;
  }

  function encode(descriptor) {
    if (!descriptor) return '';
    if (!descriptor.custom && BUILT_INS[descriptor.id]) return `${QR_PREFIX}P:${descriptor.id}`;
    const paperCode = descriptor.paper === 'a5' ? 'H' : 'V';
    return `${QR_PREFIX}C:${descriptor.mcq}:${descriptor.tf}:${descriptor.tln}:${paperCode}:${descriptor.compact ? 'K' : 'F'}`;
  }

  function decode(raw) {
    const text = String(raw || '').trim();
    if (!text) return null;

    // Backward compatibility with sheets generated by older releases.
    if (text.startsWith('TEMPLATE:')) return fromType(text.slice(9));
    if (BUILT_INS[text]) return fromType(text);
    const prefix = text.startsWith(QR_PREFIX) ? QR_PREFIX : (text.startsWith(LEGACY_QR_PREFIX) ? LEGACY_QR_PREFIX : '');
    if (!prefix) return null;

    const body = text.slice(prefix.length);
    if (body.startsWith('P:')) return fromType(body.slice(2));
    const parts = body.split(':');
    if (parts[0] === 'C' && parts.length >= 5) {
      return customDescriptor(parts[1], parts[2], parts[3], parts[4] === 'H' ? 'a5' : 'a4', parts[5] === 'K');
    }
    return null;
  }

  function qrTypst(descriptor) {
    if (typeof window.qrcode !== 'function') return '';
    const payload = encode(descriptor);
    if (!payload) return '';
    const qr = window.qrcode(0, 'M');
    qr.addData(payload);
    qr.make();
    const size = qr.getModuleCount();
    const quiet = 4;
    const gridSize = size + quiet * 2;
    const cells = [];
    for (let row = -quiet; row < size + quiet; row++) {
      for (let col = -quiet; col < size + quiet; col++) {
        const inside = row >= 0 && row < size && col >= 0 && col < size;
        cells.push(inside && qr.isDark(row, col) ? 'qb' : 'qw');
      }
    }
    return `#grid(columns: ${gridSize}, column-gutter: 0pt, row-gutter: 0pt, ${cells.join(',')})`;
  }

  function scoringFor(descriptor) {
    const totalKinds = Number(descriptor.mcq > 0) + Number(descriptor.tf > 0) + Number(descriptor.tln > 0);
    if (descriptor.mcq === 12 && descriptor.tf === 4 && descriptor.tln === 6) {
      return { mcq: { points: 0.25 }, tf: { points: [0.1, 0.25, 0.5, 1] }, tln: { points: 0.5 } };
    }
    if (totalKinds === 1 && descriptor.mcq > 0) {
      return { mcq: { points: 10 / descriptor.mcq } };
    }
    if (totalKinds === 1 && descriptor.tln > 0) {
      return { tln: { points: 10 / descriptor.tln } };
    }
    if (totalKinds === 1 && descriptor.tf > 0) {
      const scale = 10 / descriptor.tf;
      return { tf: { points: [0.1 * scale, 0.25 * scale, 0.5 * scale, scale] } };
    }
    const rawMaximum = descriptor.mcq * 0.25 + descriptor.tf + descriptor.tln * 0.5;
    const scale = rawMaximum > 0 ? 10 / rawMaximum : 0;
    return {
      mcq: { points: 0.25 * scale },
      tf: { points: [0.1 * scale, 0.25 * scale, 0.5 * scale, scale] },
      tln: { points: 0.5 * scale }
    };
  }

  function loadCache() {
    try {
      const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
      return parsed && typeof parsed === 'object' ? parsed : {};
    } catch (_) {
      return {};
    }
  }

  function persistTemplate(descriptor, template) {
    if (!descriptor || !template) return;
    const cache = loadCache();
    cache[descriptor.id] = { descriptor, template, savedAt: Date.now() };
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(cache));
    } catch (error) {
      console.warn('OMR profile cache is full; keeping profile for this session only.', error);
    }
  }

  function installTemplate(descriptor, template, aliases) {
    if (!descriptor || !template) return template;
    window.TEMPLATES = window.TEMPLATES || {};
    template.profile = descriptor;
    template.scoring = template.scoring || scoringFor(descriptor);
    window.TEMPLATES[descriptor.id] = template;
    (aliases || []).forEach(alias => { window.TEMPLATES[alias] = template; });
    persistTemplate(descriptor, template);
    return template;
  }

  function restoreTemplates() {
    const cache = loadCache();
    Object.values(cache).forEach(entry => {
      if (!entry?.descriptor || !entry?.template) return;
      window.TEMPLATES = window.TEMPLATES || {};
      window.TEMPLATES[entry.descriptor.id] = entry.template;
    });
  }

  window.OmrProfiles = {
    BUILT_INS,
    QR_PREFIX,
    customDescriptor,
    get,
    fromType,
    encode,
    decode,
    qrTypst,
    scoringFor,
    installTemplate,
    restoreTemplates
  };
})();
