export const ECOSYSTEM_LINKS = [
  {
    id: 'docs',
    icon: 'HD',
    title: 'Hướng dẫn ConicTypst',
    description: 'Tài liệu, ví dụ và API sang-math được trình bày theo từng quy trình.',
    href: 'https://hdsd-conictypst.pages.dev/',
    accent: 'blue',
  },
  {
    id: 'mixer',
    icon: 'TR',
    title: 'Trộn đề + OMR Passport',
    description: 'Trộn nhiều mã, sinh đáp án, QR và chuyển dữ liệu sang hệ thống chấm.',
    href: 'https://hdsd-conictypst.pages.dev/tron-de',
    accent: 'orange',
  },
  {
    id: 'omr',
    icon: 'OMR',
    title: 'Sang Math OMR',
    description: 'Sinh phiếu, tô đáp án, chấm camera và phân tích kết quả lớp học.',
    href: 'https://chamthi-conictypst.pages.dev/',
    accent: 'green',
  },
  {
    id: 'bank',
    icon: 'NH',
    title: 'Ngân hàng câu hỏi',
    description: 'Tổ chức kho câu hỏi Toán theo lớp, chương, mức độ và trạng thái.',
    href: 'https://hdsd-conictypst.pages.dev/ngan-hang',
    accent: 'violet',
  },
  {
    id: 'cetz',
    icon: 'CZ',
    title: 'CeTZ & Hình học',
    description: 'Vẽ hình 2D/3D, sinh mã CeTZ rồi chuyển thẳng vào Studio.',
    href: 'https://hdsd-conictypst.pages.dev/cetz-ve.html',
    accent: 'teal',
  },
  {
    id: 'tools',
    icon: '++',
    title: 'Conic Tool Hub',
    description: 'OCR, linter, atlas, Beamer, BBT Live và toàn bộ công cụ chuyên dụng.',
    href: 'https://hdsd-conictypst.pages.dev/dashboard',
    accent: 'slate',
  },
]
