-- Đợt 1 Sang Math Game Lab: bốn mode mới, dùng chung engine câu hỏi local-first.
INSERT OR IGNORE INTO products (
  id,name,eyebrow,description,image,image2,color,price_vnd,active,starter,
  sort_order,file_key,file_name,file_size,updated_at,product_type,
  fulfillment_type,access_model,access_days,delivery_url,badge,featured,
  entitlement_key
) VALUES
('dua-doi-tri-thuc','Đường Đua Tri Thức · 1 năm','Game hai đội · Gói 1 năm','Hai đội luân phiên trả lời câu hỏi KaTeX để tăng tốc về đích. Dùng chung ngân hàng câu hỏi, ảnh, màu và ZIP với Game Lab.','/previews/game-lab.png',NULL,'#06a77d',30000,1,0,4,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/dua-doi/','Dùng thử miễn phí',1,'dua-doi-tri-thuc'),
('dua-doi-tri-thuc-2y','Đường Đua Tri Thức · 2 năm','Game hai đội · Gói 2 năm','Hai đội luân phiên trả lời câu hỏi KaTeX để tăng tốc về đích. Dùng chung ngân hàng câu hỏi, ảnh, màu và ZIP với Game Lab.','/previews/game-lab.png',NULL,'#06a77d',50000,1,0,5,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/dua-doi/','Phổ biến',1,'dua-doi-tri-thuc'),
('dua-doi-tri-thuc-5y','Đường Đua Tri Thức · 5 năm','Game hai đội · Gói 5 năm','Hai đội luân phiên trả lời câu hỏi KaTeX để tăng tốc về đích. Dùng chung ngân hàng câu hỏi, ảnh, màu và ZIP với Game Lab.','/previews/game-lab.png',NULL,'#06a77d',100000,1,0,6,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/dua-doi/','Tiết kiệm nhất',1,'dua-doi-tri-thuc'),

('manh-ghep-bi-an','Mảnh Ghép Bí Ẩn · 1 năm','Khám phá hình ảnh · Gói 1 năm','Mỗi đáp án đúng mở một mảnh của hình bí mật; hỗ trợ KaTeX, ảnh riêng và trình chiếu cho cả lớp.','/previews/game-lab.png',NULL,'#8b5cf6',30000,1,0,7,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/manh-ghep/','Dùng thử miễn phí',1,'manh-ghep-bi-an'),
('manh-ghep-bi-an-2y','Mảnh Ghép Bí Ẩn · 2 năm','Khám phá hình ảnh · Gói 2 năm','Mỗi đáp án đúng mở một mảnh của hình bí mật; hỗ trợ KaTeX, ảnh riêng và trình chiếu cho cả lớp.','/previews/game-lab.png',NULL,'#8b5cf6',50000,1,0,8,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/manh-ghep/','Phổ biến',1,'manh-ghep-bi-an'),
('manh-ghep-bi-an-5y','Mảnh Ghép Bí Ẩn · 5 năm','Khám phá hình ảnh · Gói 5 năm','Mỗi đáp án đúng mở một mảnh của hình bí mật; hỗ trợ KaTeX, ảnh riêng và trình chiếu cho cả lớp.','/previews/game-lab.png',NULL,'#8b5cf6',100000,1,0,9,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/manh-ghep/','Tiết kiệm nhất',1,'manh-ghep-bi-an'),

('san-kho-bau','Hành Trình Kho Báu · 1 năm','Phiêu lưu theo chặng · Gói 1 năm','Vượt từng mốc bằng câu hỏi và thu thập kho báu tri thức; tối ưu cho ôn tập theo tiến trình.','/previews/game-lab.png',NULL,'#d69b2d',30000,1,0,10,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/san-kho-bau/','Dùng thử miễn phí',1,'san-kho-bau'),
('san-kho-bau-2y','Hành Trình Kho Báu · 2 năm','Phiêu lưu theo chặng · Gói 2 năm','Vượt từng mốc bằng câu hỏi và thu thập kho báu tri thức; tối ưu cho ôn tập theo tiến trình.','/previews/game-lab.png',NULL,'#d69b2d',50000,1,0,11,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/san-kho-bau/','Phổ biến',1,'san-kho-bau'),
('san-kho-bau-5y','Hành Trình Kho Báu · 5 năm','Phiêu lưu theo chặng · Gói 5 năm','Vượt từng mốc bằng câu hỏi và thu thập kho báu tri thức; tối ưu cho ôn tập theo tiến trình.','/previews/game-lab.png',NULL,'#d69b2d',100000,1,0,12,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/san-kho-bau/','Tiết kiệm nhất',1,'san-kho-bau'),

('vong-quay-thu-thach','Vòng Quay Thử Thách · 1 năm','Cả lớp cùng chơi · Gói 1 năm','Vòng quay chọn thử thách ngẫu nhiên, kết hợp ngân hàng câu hỏi KaTeX và phản hồi trực tiếp.','/previews/game-lab.png',NULL,'#2876d2',30000,1,0,13,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/vong-quay/','Dùng thử miễn phí',1,'vong-quay-thu-thach'),
('vong-quay-thu-thach-2y','Vòng Quay Thử Thách · 2 năm','Cả lớp cùng chơi · Gói 2 năm','Vòng quay chọn thử thách ngẫu nhiên, kết hợp ngân hàng câu hỏi KaTeX và phản hồi trực tiếp.','/previews/game-lab.png',NULL,'#2876d2',50000,1,0,14,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/vong-quay/','Phổ biến',1,'vong-quay-thu-thach'),
('vong-quay-thu-thach-5y','Vòng Quay Thử Thách · 5 năm','Cả lớp cùng chơi · Gói 5 năm','Vòng quay chọn thử thách ngẫu nhiên, kết hợp ngân hàng câu hỏi KaTeX và phản hồi trực tiếp.','/previews/game-lab.png',NULL,'#2876d2',100000,1,0,15,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/vong-quay/','Tiết kiệm nhất',1,'vong-quay-thu-thach');
