-- Đợt 2 Sang Math Game Lab: bốn mode mới, tiếp tục dùng chung dữ liệu IndexedDB.
INSERT OR IGNORE INTO products (
  id,name,eyebrow,description,image,image2,color,price_vnd,active,starter,
  sort_order,file_key,file_name,file_size,updated_at,product_type,
  fulfillment_type,access_model,access_days,delivery_url,badge,featured,
  entitlement_key
) VALUES
('do-min-toan-hoc','Dò Mìn Toán Học · 1 năm','Game sinh tồn · Gói 1 năm','Ba mạng để vượt ma trận câu hỏi; trả lời đúng mở ô an toàn, trả lời sai chạm mìn. Dùng chung KaTeX, hình ảnh và ZIP với Game Lab.','/previews/game-lab-wave2.png',NULL,'#d9574f',30000,1,0,16,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/do-min/','Dùng thử miễn phí',1,'do-min-toan-hoc'),
('do-min-toan-hoc-2y','Dò Mìn Toán Học · 2 năm','Game sinh tồn · Gói 2 năm','Ba mạng để vượt ma trận câu hỏi; trả lời đúng mở ô an toàn, trả lời sai chạm mìn. Dùng chung KaTeX, hình ảnh và ZIP với Game Lab.','/previews/game-lab-wave2.png',NULL,'#d9574f',50000,1,0,17,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/do-min/','Phổ biến',1,'do-min-toan-hoc'),
('do-min-toan-hoc-5y','Dò Mìn Toán Học · 5 năm','Game sinh tồn · Gói 5 năm','Ba mạng để vượt ma trận câu hỏi; trả lời đúng mở ô an toàn, trả lời sai chạm mìn. Dùng chung KaTeX, hình ảnh và ZIP với Game Lab.','/previews/game-lab-wave2.png',NULL,'#d9574f',100000,1,0,18,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/do-min/','Tiết kiệm nhất',1,'do-min-toan-hoc'),

('doan-tau-logic','Đoàn Tàu Logic · 1 năm','Lắp toa tri thức · Gói 1 năm','Mỗi đáp án đúng nối thêm một toa vào đoàn tàu; phù hợp ôn tập theo tiến trình trên màn chiếu.','/previews/game-lab-wave2.png',NULL,'#1b9b82',30000,1,0,19,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/doan-tau/','Dùng thử miễn phí',1,'doan-tau-logic'),
('doan-tau-logic-2y','Đoàn Tàu Logic · 2 năm','Lắp toa tri thức · Gói 2 năm','Mỗi đáp án đúng nối thêm một toa vào đoàn tàu; phù hợp ôn tập theo tiến trình trên màn chiếu.','/previews/game-lab-wave2.png',NULL,'#1b9b82',50000,1,0,20,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/doan-tau/','Phổ biến',1,'doan-tau-logic'),
('doan-tau-logic-5y','Đoàn Tàu Logic · 5 năm','Lắp toa tri thức · Gói 5 năm','Mỗi đáp án đúng nối thêm một toa vào đoàn tàu; phù hợp ôn tập theo tiến trình trên màn chiếu.','/previews/game-lab-wave2.png',NULL,'#1b9b82',100000,1,0,21,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/doan-tau/','Tiết kiệm nhất',1,'doan-tau-logic'),

('ban-co-thu-thach','Bàn Cờ Thử Thách · 1 năm','Hai người theo lượt · Gói 1 năm','Hai người luân phiên trả lời, tung xúc xắc và tiến qua bàn cờ 20 ô với phản hồi trực tiếp.','/previews/game-lab-wave2.png',NULL,'#6259b8',30000,1,0,22,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/ban-co/','Dùng thử miễn phí',1,'ban-co-thu-thach'),
('ban-co-thu-thach-2y','Bàn Cờ Thử Thách · 2 năm','Hai người theo lượt · Gói 2 năm','Hai người luân phiên trả lời, tung xúc xắc và tiến qua bàn cờ 20 ô với phản hồi trực tiếp.','/previews/game-lab-wave2.png',NULL,'#6259b8',50000,1,0,23,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/ban-co/','Phổ biến',1,'ban-co-thu-thach'),
('ban-co-thu-thach-5y','Bàn Cờ Thử Thách · 5 năm','Hai người theo lượt · Gói 5 năm','Hai người luân phiên trả lời, tung xúc xắc và tiến qua bàn cờ 20 ô với phản hồi trực tiếp.','/previews/game-lab-wave2.png',NULL,'#6259b8',100000,1,0,24,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/ban-co/','Tiết kiệm nhất',1,'ban-co-thu-thach'),

('ghep-cap-than-toc','Ghép Cặp Thần Tốc · 1 năm','Nối câu hỏi–đáp án · Gói 1 năm','Chọn câu hỏi rồi tìm đúng đáp án đã xáo trộn; hỗ trợ KaTeX, hình ảnh và tối ưu cho chuột lẫn cảm ứng.','/previews/game-lab-wave2.png',NULL,'#a755c2',30000,1,0,25,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/ghep-cap/','Dùng thử miễn phí',1,'ghep-cap-than-toc'),
('ghep-cap-than-toc-2y','Ghép Cặp Thần Tốc · 2 năm','Nối câu hỏi–đáp án · Gói 2 năm','Chọn câu hỏi rồi tìm đúng đáp án đã xáo trộn; hỗ trợ KaTeX, hình ảnh và tối ưu cho chuột lẫn cảm ứng.','/previews/game-lab-wave2.png',NULL,'#a755c2',50000,1,0,26,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/ghep-cap/','Phổ biến',1,'ghep-cap-than-toc'),
('ghep-cap-than-toc-5y','Ghép Cặp Thần Tốc · 5 năm','Nối câu hỏi–đáp án · Gói 5 năm','Chọn câu hỏi rồi tìm đúng đáp án đã xáo trộn; hỗ trợ KaTeX, hình ảnh và tối ưu cho chuột lẫn cảm ứng.','/previews/game-lab-wave2.png',NULL,'#a755c2',100000,1,0,27,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/ghep-cap/','Tiết kiệm nhất',1,'ghep-cap-than-toc');
