-- Đợt 3 Sang Math Game Lab: bốn mode lớp học mới, dùng chung cổng nhập Word/Excel.
INSERT OR IGNORE INTO products (
  id,name,eyebrow,description,image,image2,color,price_vnd,active,starter,
  sort_order,file_key,file_name,file_size,updated_at,product_type,
  fulfillment_type,access_model,access_days,delivery_url,badge,featured,
  entitlement_key
) VALUES
('hop-qua-bi-mat','Hộp Quà Bí Mật · 1 năm','Mở quà nhận sao · Gói 1 năm','Mỗi câu trả lời đúng mở một hộp quà và nhận sao ngẫu nhiên; nhập nhanh bằng Word, Excel, CSV hoặc JSON.','/previews/game-lab-wave3.png',NULL,'#c77b26',30000,1,0,28,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/hop-qua/','Dùng thử miễn phí',1,'hop-qua-bi-mat'),
('hop-qua-bi-mat-2y','Hộp Quà Bí Mật · 2 năm','Mở quà nhận sao · Gói 2 năm','Mỗi câu trả lời đúng mở một hộp quà và nhận sao ngẫu nhiên; nhập nhanh bằng Word, Excel, CSV hoặc JSON.','/previews/game-lab-wave3.png',NULL,'#c77b26',50000,1,0,29,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/hop-qua/','Phổ biến',1,'hop-qua-bi-mat'),
('hop-qua-bi-mat-5y','Hộp Quà Bí Mật · 5 năm','Mở quà nhận sao · Gói 5 năm','Mỗi câu trả lời đúng mở một hộp quà và nhận sao ngẫu nhiên; nhập nhanh bằng Word, Excel, CSV hoặc JSON.','/previews/game-lab-wave3.png',NULL,'#c77b26',100000,1,0,30,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/hop-qua/','Tiết kiệm nhất',1,'hop-qua-bi-mat'),

('bingo-toan-hoc','Bingo Toán Học · 1 năm','Cả lớp săn hàng · Gói 1 năm','Đánh dấu bảng Bingo qua từng đáp án đúng; thích hợp khởi động, luyện nhanh và củng cố cuối tiết.','/previews/game-lab-wave3.png',NULL,'#238b68',30000,1,0,31,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/bingo/','Dùng thử miễn phí',1,'bingo-toan-hoc'),
('bingo-toan-hoc-2y','Bingo Toán Học · 2 năm','Cả lớp săn hàng · Gói 2 năm','Đánh dấu bảng Bingo qua từng đáp án đúng; thích hợp khởi động, luyện nhanh và củng cố cuối tiết.','/previews/game-lab-wave3.png',NULL,'#238b68',50000,1,0,32,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/bingo/','Phổ biến',1,'bingo-toan-hoc'),
('bingo-toan-hoc-5y','Bingo Toán Học · 5 năm','Cả lớp săn hàng · Gói 5 năm','Đánh dấu bảng Bingo qua từng đáp án đúng; thích hợp khởi động, luyện nhanh và củng cố cuối tiết.','/previews/game-lab-wave3.png',NULL,'#238b68',100000,1,0,33,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/bingo/','Tiết kiệm nhất',1,'bingo-toan-hoc'),

('ten-lua-tri-thuc','Tên Lửa Tri Thức · 1 năm','Phóng lên từng chặng · Gói 1 năm','Tích năng lượng bằng câu trả lời đúng và đưa tên lửa chạm quỹ đạo; trình chiếu rõ trên màn hình lớp.','/previews/game-lab-wave3.png',NULL,'#5967cf',30000,1,0,34,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/ten-lua/','Dùng thử miễn phí',1,'ten-lua-tri-thuc'),
('ten-lua-tri-thuc-2y','Tên Lửa Tri Thức · 2 năm','Phóng lên từng chặng · Gói 2 năm','Tích năng lượng bằng câu trả lời đúng và đưa tên lửa chạm quỹ đạo; trình chiếu rõ trên màn hình lớp.','/previews/game-lab-wave3.png',NULL,'#5967cf',50000,1,0,35,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/ten-lua/','Phổ biến',1,'ten-lua-tri-thuc'),
('ten-lua-tri-thuc-5y','Tên Lửa Tri Thức · 5 năm','Phóng lên từng chặng · Gói 5 năm','Tích năng lượng bằng câu trả lời đúng và đưa tên lửa chạm quỹ đạo; trình chiếu rõ trên màn hình lớp.','/previews/game-lab-wave3.png',NULL,'#5967cf',100000,1,0,36,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/ten-lua/','Tiết kiệm nhất',1,'ten-lua-tri-thuc'),

('vuot-song-thu-thach','Vượt Sông Thử Thách · 1 năm','Bắc cầu kiến thức · Gói 1 năm','Mỗi đáp án đúng đặt thêm một nhịp cầu an toàn; trực quan, dễ tổ chức cho cá nhân hoặc cả đội.','/previews/game-lab-wave3.png',NULL,'#2385a5',30000,1,0,37,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',365,'https://sang-math-store.pages.dev/games/vuot-song/','Dùng thử miễn phí',1,'vuot-song-thu-thach'),
('vuot-song-thu-thach-2y','Vượt Sông Thử Thách · 2 năm','Bắc cầu kiến thức · Gói 2 năm','Mỗi đáp án đúng đặt thêm một nhịp cầu an toàn; trực quan, dễ tổ chức cho cá nhân hoặc cả đội.','/previews/game-lab-wave3.png',NULL,'#2385a5',50000,1,0,38,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',730,'https://sang-math-store.pages.dev/games/vuot-song/','Phổ biến',1,'vuot-song-thu-thach'),
('vuot-song-thu-thach-5y','Vượt Sông Thử Thách · 5 năm','Bắc cầu kiến thức · Gói 5 năm','Mỗi đáp án đúng đặt thêm một nhịp cầu an toàn; trực quan, dễ tổ chức cho cá nhân hoặc cả đội.','/previews/game-lab-wave3.png',NULL,'#2385a5',100000,1,0,39,NULL,NULL,NULL,datetime('now'),'game','web_access','subscription',1825,'https://sang-math-store.pages.dev/games/vuot-song/','Tiết kiệm nhất',1,'vuot-song-thu-thach');
