INSERT OR IGNORE INTO products (
  id,name,eyebrow,description,image,image2,color,price_vnd,active,starter,
  sort_order,file_key,file_name,file_size,updated_at,product_type,
  fulfillment_type,access_model,access_days,delivery_url,badge,featured,
  entitlement_key
) VALUES (
  'hub-cloud-1y',
  'Gói Cloud Storage · 1 năm',
  'Lưu trữ an toàn trên TypstConicHub',
  'Kích hoạt 365 ngày lưu trữ Cloud cho Workspace của bạn.',
  '/previews/game-lab.png',
  NULL,
  '#16a34a',
  199000,
  1,
  0,
  91,
  NULL,
  NULL,
  NULL,
  datetime('now'),
  'account',
  'web_access',
  'subscription',
  365,
  'https://typstconichub.pages.dev/',
  'Nâng cấp 1 Năm',
  1,
  'typstconichub-cloud'
), (
  'hub-cloud-2y',
  'Gói Cloud Storage · 2 năm',
  'Lưu trữ an toàn trên TypstConicHub',
  'Kích hoạt 730 ngày lưu trữ Cloud cho Workspace của bạn.',
  '/previews/game-lab.png',
  NULL,
  '#16a34a',
  299000,
  1,
  0,
  92,
  NULL,
  NULL,
  NULL,
  datetime('now'),
  'account',
  'web_access',
  'subscription',
  730,
  'https://typstconichub.pages.dev/',
  'Nâng cấp 2 Năm',
  1,
  'typstconichub-cloud'
), (
  'hub-cloud-5y',
  'Gói Cloud Storage · 5 năm',
  'Lưu trữ an toàn trên TypstConicHub',
  'Kích hoạt 1825 ngày lưu trữ Cloud cho Workspace của bạn.',
  '/previews/game-lab.png',
  NULL,
  '#16a34a',
  499000,
  1,
  0,
  93,
  NULL,
  NULL,
  NULL,
  datetime('now'),
  'account',
  'web_access',
  'subscription',
  1825,
  'https://typstconichub.pages.dev/',
  'Nâng cấp 5 Năm',
  1,
  'typstconichub-cloud'
);
